### ISSUE TITLE
Allow custom density estimators in slabinterval

### ISSUE THREAD

**Issue by mjskay** [mjskay/ggdist#113]
Basic idea would be to create a family of functions for use with stat_slabinterval in a similar style to the approach used for stats/geoms/positions in ggplot for handling different types of density estimators. E.g. things like `density = "kde"` or `density = "histogram"` or `density = "bounded"` or `density = density_bounded(some_options =...)`.

This would replace the current `slab_type = "pdf"` / `slab_type = "histogram"` sometime after #83 is done.

- [x] allow custom density estimators with `density = `
- ~~[ ] -> replace `slab_type = "histogram"` with `density = "histogram"`~~ #165

**Comment by tomicapretto** [comment]
I've uploaded code about KDEs and bandwidth estimators to this gist https://gist.github.com/tomicapretto/74f90f3ad026f397fa11f2797eb7a954. Let me know if anything there looks helpful.

Happy to help you if there's something you want to adapt, or if you have any questions, or whatever that can help with this issue.
