### ISSUE TITLE
Plot stats no longer work without loading the package

### ISSUE THREAD

**Issue by dmphillippo** [mjskay/ggdist#128]
Prior to the 3.1.0 release, you could call a ggdist stat without loading the package, e.g.
```r
library(ggplot2)
ggplot(data.frame(x = rnorm(1000), y = "Test"), aes(x = x, y = y)) + ggdist::stat_halfeye()
```

However, as of 3.1.0 the above now fails with the following warning:
```r
> Warning message:
> Computation failed in `stat_slabinterval()`:
> object 'median_qi' of mode 'function' was not found 
```

I think this is due to a change in the default value for the `point_interval` argument. Previously this was `median_qi`, which got picked up from the package namespace correctly; now this is `"median_qi"`, and the corresponding function then does not get found unless the package is loaded.

The only way to get the above to work without loading the package is
```r
ggplot(data.frame(x = rnorm(1000), y = "Test"), aes(x = x, y = y)) + ggdist::stat_halfeye(point_interval = ggdist::median_qi)
```

Some wider context: this seems to break packages which rely on ggdist and have ggdist in Imports but not Depends (since the package is not loaded), and construct plots with `ggdist::stat_*`.

Huge thanks for all your work on ggdist, it is really excellent!

**Comment by mjskay** [comment]
Ah shoot, yeah that is problematic. Need to reconstruct why I made that change; there is probably a better solution.

**Comment by mjskay** [comment]
Yeah, this is related to the new codegen stuff. I should be able to put together a fix it just might be a little hairy.

**Comment by mjskay** [comment]
Oh yeah, that's great! Well there's a test for that now so that behavior should be permanent ;)

Thanks again!

**Comment by mjskay** [comment]
FYI: this fix is now on cran

**Comment by dmphillippo** [comment]
Brilliant, thanks so much!
