### ISSUE TITLE
stat_lineribbon missing parameters?

### ISSUE THREAD

**Issue by zacksteel** [mjskay/ggdist#131]
Thanks for the great package(s)

I'd like adjust individual line or ribbon aesthetics for the line or ribbon components of this function similar to what is possible with e.g., geom_pointinterval (e.g., interval_alpha & point_alpha). Something like this:

m_mpg = brm(
  mpg ~ hp * cyl, 
  data = mtcars, 
  
  file = "models/tidy-brms_m_mpg.rds"  # cache model (can be removed)
)

mtcars %>%
  group_by(cyl) %>%
  data_grid(hp = seq_range(hp, n = 51)) %>%
  add_epred_draws(m_mpg) %>%
  ggplot(aes(x = hp, y = mpg, color = ordered(cyl))) +
  stat_lineribbon(aes(y = .epred), ribbon_alpha = 0.5) + ## note change from tutorial here
  geom_point(data = mtcars) +
  scale_fill_brewer(palette = "Greys") +
  scale_color_brewer(palette = "Set2")

But this gives a warning
Warning message:
Ignoring unknown parameters: ribbon_alpha 

Is it possible to add this flexibility or am I just mis-specifying the function?

Thanks,
Zack

**Comment by mjskay** [comment]
Yeah --- currently lineribbon does not have sub-geometry-specific like slabinterval does, though it is on my todo list. See #40 and some workarounds discussed there.

**Comment by zacksteel** [comment]
ok thanks for pointing me toward the workarounds and thanks again for the great package
