### ISSUE TITLE
Arrange dots when group is NA

### ISSUE THREAD

**Issue by Ari04T** [mjskay/ggdist#132]
Hello!

I'm having a bit of an issue here. I want to do a plot such as the one shown below, but I want the colors to be organized—meaning all the green dots should be at the bottom and all the orange ones should be at the top.

![plot](https://mjskay.github.io/ggdist/articles/dotsinterval_files/figure-html/beeswarm_shape_color_together-1.png)

I've tried to do this by setting the color/fill as an ordered factor, but the dots still seem to show up in random fashion. Is there a way to order the color of the dots?

Thanks!

**Comment by mjskay** [comment]
Good question! In the released version, the dots are ordered by the data values (e.g. by the y values above), hence the seemingly-random order.

Being able to order them to create a "stacking" effect is a good idea. I just created a modification that supports this by mapping a variable onto an optional `order` aesthetic, which will determine the order of the dots within each bin. You can try it by installing the development version (`remotes::install_github("mjskay/ggdist")`). It looks like this:

```r
abcc_df %>%
  ggplot(aes(y = value, x = abc, shape = abc, color = hi, group = NA, order = hi)) +
  geom_dots() +
  scale_color_brewer(palette = "Dark2")
```
![image](https://user-images.githubusercontent.com/6345019/162359460-5507dbd3-efe3-41cd-b3c1-4a1eae4a2788.png)

Does that help?

**Comment by Ari04T** [comment]
Awesome, exactly what I was looking for. Thanks man.

**Comment by mjskay** [comment]
No problem!
