### ISSUE TITLE
Add new linewidth aes

### ISSUE THREAD

**Issue by mjskay** [mjskay/ggdist#138]
See here: https://twitter.com/thomasp85/status/1537024892293599235?t=FEzmrpgT2HymjRMp8Fn2uQ&s=19

This is probably going to involve some disentangling (and deprecating) of things like point_size and interval_size and such.

**Comment by mjskay** [comment]
Might also be an opportunity to change the default mapping in pointinterval to use `level` instead of `.width` so that legends are more sensible by default. Have to double check if warnings are generated though (hopefully not for ordinal variables?). See #147.

**Comment by mjskay** [comment]
- [ ] `stat()` -> `after_stat()`

**Comment by mjskay** [comment]
- [ ] update vignette diagrams

**Comment by psychelzh** [comment]
Yes! Currently, say `stat_dotsinterval()` will gives warning after {ggplot2} upgrades to 3.4.0.

```bash
Warning: Using the `size` aesthietic with geom_segment was deprecated in ggplot2 3.4.0. Please use the `linewidth` aesthetic instead.
```

**Comment by mjskay** [comment]
Yup, see the ggplot34 branch of ggdist for a mostly complete fix (still needs a bit of polish): https://github.com/mjskay/ggdist/tree/ggplot3.4
