### ISSUE TITLE
geom_dots: sort the stacking by color

### ISSUE THREAD

**Issue by DominiqueMakowski** [mjskay/ggdist#143]
Hi! I have a case similar to the following:

``` r
library(ggplot2)
library(ggdist)

data <- iris
data$color <- cut(data$Petal.Length, 3, labels = c("red", "blue", "green"))
data$Sepal.Length <- round(data$Sepal.Length, 0)
data$y <- ifelse(data$Petal.Width > mean(data$Petal.Width), 1, 0)
data$side <- ifelse(data$y == 1, "bottom", "top")

ggplot(data) +
  geom_dots(
    aes(x = Sepal.Length, y = y, group = Petal.Width, side = side), 
    fill = data$color, color = NA
    ) 
```

![](https://i.imgur.com/8oJEOFM.png)

<sup>Created on 2022-08-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I am stacking dots (for a binomial model, hence the y-axis is 0-1 with dots on the top and bottom). These dots are filled with some other value (in my case, it's not passed via an aesthetic). I wonder if it's possible to stack the dots by color (for instance, red first, then blue etc.)

I tried arranging the data but this actually changes the color, which I'm not exactly sure why 🤔 

``` r
ggplot(data) +
  geom_dots(
    data = dplyr::arrange(data, color),
    aes(x = Sepal.Length, y = y, group = Petal.Width, side = side), 
    fill = data$color, color = NA
    ) 
```

![](https://i.imgur.com/jku43wO.png)

<sup>Created on 2022-08-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mjskay** [comment]
Should be doable as of the recently-released version 3.2 --- I added an `order` aesthetic which determines the sort order of elements in the bins. See the second example under *Varying discrete aesthetics within dot groups* here: https://mjskay.github.io/ggdist/articles/dotsinterval.html#varying-discrete-aesthetics-within-dot-groups

Does that help?

**Comment by DominiqueMakowski** [comment]
Sorry I missed that! It looks like exactly what I'd need but it doesn't seem to work (I reinstalled the latest GH version) 

``` r
library(ggplot2)
library(ggdist)

data <- iris
data$color <- cut(data$Petal.Length, 3, labels = c("red", "green", "blue"))
data$Sepal.Length <- round(data$Sepal.Length, 0)
data$y <- ifelse(data$Petal.Width > mean(data$Petal.Width), 1, 0)
data$side <- ifelse(data$y == 1, "bottom", "top")

ggplot(data) +
  geom_dots(
    aes(x = Sepal.Length, y = y, group = Petal.Width, side = side, fill=color, order = color)
  ) 
```

![](https://i.imgur.com/8SQKzSx.png)

``` r
Ⰰ0
#> Error in eval(expr, envir, enclos): object 'Ⰰ0' not found
```

<sup>Created on 2022-08-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DominiqueMakowski** [comment]
Found! it was messing with the group aesthetic, once I removed it it works :) thanks a lot!

``` r
library(ggplot2)
library(ggdist)

data <- iris
data$color <- cut(data$Petal.Length, 3, labels = c("red", "green", "blue"))
data$Sepal.Length <- round(data$Sepal.Length, 0)
data$y <- ifelse(data$Petal.Width > mean(data$Petal.Width), 1, 0)
data$side <- ifelse(data$y == 1, "bottom", "top")

ggplot(data) +
  geom_dots(
    aes(x = Sepal.Length, y = y, side = side, order = color),
    fill=data$color
  ) 
```

![](https://i.imgur.com/6xruBsr.png)

<sup>Created on 2022-08-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mjskay** [comment]
No prob!

Aside: I believe the "canonical" way to pass through specific values to an aesthetic without having them adjusted by the scale function (as you are doing with `fill`) is to wrap them in `I()`. Something like this:

```r
ggplot(data) +
  geom_dots(
    aes(x = Sepal.Length, y = y, side = side, fill = I(color), order = color)
  )
```

**Comment by DominiqueMakowski** [comment]
Thanks for the hint :)

it's too beautiful now 🥲
 
![image](https://user-images.githubusercontent.com/8875533/182518978-a6993c21-ca1e-4667-a776-3566cc96ae0b.png)

**Comment by mjskay** [comment]
wow! pretty :)

**Comment by DominiqueMakowski** [comment]
(wrapping inside `I()` doesn't seem to work though, but I'll look into that once I stop marvelling at my plots)

**Comment by DominiqueMakowski** [comment]
Another minor remark, I try setting up order as an interaction with `side` to have for instance the red dots always on the "top", but it doesn't seem to be taken into account as well:

Here, the blue dots are always close to the bottom or top (depending on side) regardless of the interaction:

``` r
library(ggplot2)
library(ggdist)

data <- iris
data$color <- cut(data$Sepal.Width, 3, labels = c("red", "green", "blue"))
data$x <- as.numeric(cut(data$Sepal.Length, 4, labels = 1:4))
data$y <- ifelse(data$Petal.Width > mean(data$Petal.Width), 1, 0)
data$side <- ifelse(data$y == 1, "bottom", "top")

ggplot(data) +
  geom_dots(
    aes(x = x, y = y, side = side, order = interaction(color, side)),
    fill=data$color
  ) 
```

![](https://i.imgur.com/QUKdNOQ.png)

``` r
# Same as:

ggplot(data) +
  geom_dots(
    aes(x = x, y = y, side = side, order = color),
    fill=data$color
  ) 
```

![](https://i.imgur.com/dXmIEny.png)

``` r
ﬀƴ
#> Error in eval(expr, envir, enclos): object 'ﬀƴ' not found
```

<sup>Created on 2022-08-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mjskay** [comment]
You seem to have overlapping dots because your y value is numeric and not a factor (so ggplot doesn't automatically group by y, which means you actually have multiple dotplots at each y position). This is making it hard to see what the chart is doing --- one easy solution is to add a `group = y` aesthetic.

Then you can adjust the order of colors for different sides by reversing its order within one group (e.g. by multiplying it by -1). Something like this:

```r
ggplot(data) + 
  geom_dots(aes(
    x = x, y = y, side = side, 
    order = as.numeric(color) * ifelse(y == 1, 1, -1), 
    group = y, 
    fill = I(color)
  ),
  scale = 0.75
)
```
![image](https://user-images.githubusercontent.com/6345019/182535379-c3b0024c-6c1f-4fad-9ba3-b71f4a52e985.png)

Is that what you were looking for?
