### ISSUE TITLE
Possible to set interval_size while also showing multiple interval lengths?

### ISSUE THREAD

**Issue by rcalinjageman** [mjskay/ggdist#152]
I'm guessing this is not possible, but I'm wondering if there is a way to be able to use .width to plot multiple intervals while also setting interval_size?  Currently, if you use .width then ggdist automatically scales each interval to a different line thickness (plots the 90% CI thicker than the 95% CI, etc).  But if you set interval_size this goes away -- each interval in .width is plotted at the same thickness, so the longest one obscures the others.  Is it possible to make it so that interval_size just sets the starting point for the automatic adjustments done for each value in .width?

Here's what I've been using to plot 90 and 95% CIs together with .width

```
  myplot <- myplot + ggdist::stat_dist_halfeye(
    data = gdata,
    orientation = 'vertical',
    ggplot2::aes(
      x = x_value,
      y = y_value,
      dist = distributional::dist_student_t(
        df = df,
        mu = y_value,
        sigma = SE
      )
    ),
  .width = c(0.9,0.95),
  normalize = 'groups'
  )
```

When I add interval_size both 90% and 95% CIs take on the value, so the 90% CI is masked:

```
  myplot <- myplot + ggdist::stat_dist_halfeye(
    data = gdata,
    orientation = 'vertical',
    ggplot2::aes(
      x = x_value,
      y = y_value,
      dist = distributional::dist_student_t(
        df = df,
        mu = y_value,
        sigma = SE
      )
    ),
  .width = c(0.9,0.95),
  invterval_size = 3,
  normalize = 'groups'
  )
```

For the moment, I'm working around this by manually adding in the 90% CI... but figured I'd ask in case I'd missed something or if it might be something that could be tweaked in future releases.  

As usual, thanks -- this package is amazing.

**Comment by rcalinjageman** [comment]
Oh, yeah - that's it -- thanks.

**Comment by mjskay** [comment]
Great! happy to help.
