### ISSUE TITLE
`geom_interval`s overlaid in the different orders within the same plot

### ISSUE THREAD

**Issue by damonbayer** [mjskay/ggdist#155]
In some instances, it is possible for two `geom_interval`s in the same plot to overlaid in different orders, within the same plot. I'm not sure if this is a more general `ggplot2` bug (or if I have simply misunderstood how things are supposed to work), but I've only been able to reproduce it with `geom_interval`.

I think this is not supposed to happen, but, if it is, can someone explain how to avoid it?

Here I create some data and plot it. The plot looks as I expected, with consistent overlapping order in each of the two y values.

``` r
library(ggplot2)
library(ggdist)

dat <-
  data.frame(
    x = c(2, 2, 2, 2),
    y = c(0, 1, 0, 1),
    xmin = c(1, 1, 0, 0),
    xmax = c(4, 4, 3, 3),
    color = c("a", "a", "b", "b")
  )

dat |>
  ggplot(aes(x = x, y = y, xmin = xmin, xmax = xmax, color = color)) +
  geom_interval(alpha = 0.5)
```

![](https://i.imgur.com/0DTiaz0.png)

If I slightly perturb the data, changing one value by `3.3e-16`, everything still looks as good.

``` r

dat |>
  transform(xmin = xmin + c(0, 3.3e-16, 0, 0)) |>
  ggplot(aes(x = x, y = y, xmin = xmin, xmax = xmax, color = color)) +
  geom_interval()
```

![](https://i.imgur.com/ecQWlf0.png)

However, If I slightly perturb the data a bit more, changing one value by `3.4e-16`, the overlapping for `y = 1` changes so that the the intervals at each level no longer have the same overlapping color. I'm not sure why this would ever happen, and I especially don't understand why changing one value by `3.4e-16` would cause it to happen.

``` r

dat |>
  transform(xmin = xmin + c(0, 3.4e-16, 0, 0)) |>
  ggplot(aes(x = x, y = y, xmin = xmin, xmax = xmax, color = color)) +
  geom_interval()
```

![](https://i.imgur.com/PFN7hnB.png)

Here's my session info:

``` r

sessionInfo()
#> R version 4.2.1 (2022-06-23)
#> Platform: aarch64-apple-darwin20 (64-bit)
#> Running under: macOS Monterey 12.6
#> 
#> Matrix products: default
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] ggdist_3.2.0  ggplot2_3.3.6
#> 
#> loaded via a namespace (and not attached):
#>  [1] pillar_1.8.1         compiler_4.2.1       highr_0.9           
#>  [4] R.methodsS3_1.8.2    R.utils_2.12.0       tools_4.2.1         
#>  [7] digest_0.6.30        evaluate_0.17        lifecycle_1.0.3     
#> [10] tibble_3.1.8         gtable_0.3.1         R.cache_0.16.0      
#> [13] pkgconfig_2.0.3      rlang_1.0.6          reprex_2.0.2        
#> [16] DBI_1.1.3            cli_3.4.1            rstudioapi_0.14     
#> [19] yaml_2.3.5           xfun_0.33            fastmap_1.1.0       
#> [22] dplyr_1.0.10         withr_2.5.0          styler_1.7.0        
#> [25] stringr_1.4.1        knitr_1.40           generics_0.1.3      
#> [28] fs_1.5.2             vctrs_0.5.0          tidyselect_1.2.0    
#> [31] grid_4.2.1           glue_1.6.2           R6_2.5.1            
#> [34] fansi_1.0.3          distributional_0.3.1 rmarkdown_2.17      
#> [37] farver_2.1.1         purrr_0.3.5          magrittr_2.0.3      
#> [40] scales_1.2.1         htmltools_0.5.3      assertthat_0.2.1    
#> [43] colorspace_2.0-3     labeling_0.4.2       utf8_1.2.2          
#> [46] stringi_1.7.8        munsell_0.5.0        R.oo_1.25.0
```

<sup>Created on 2022-10-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mjskay** [comment]
Yeah, this is intended behavior --- geom_interval reorders intervals so that larger ones are towards the back. This is a bit of a weird hack, I admit, but it ensures that typical use cases (nested intervals) are drawn correctly. It also helps make overlapping sets of intervals from different groups with varying `alpha` levels more legible. e.g. this example from the [tidybayes vignette](https://mjskay.github.io/tidybayes/articles/tidy-brms.html#ordinal-models) (using geom_lineribbon, but geom_interval shares the same code) works because of it:

![image](https://user-images.githubusercontent.com/6345019/215373195-3a93c1cb-4b1a-4ee2-8384-dcbd17b21394.png)

If geom_interval isn't working for your use case, I'd give the less specialized `ggplot2::geom_linerange()` a try. It should not reorder intervals.
