### ISSUE TITLE
Error with rvar and curve_interval

### ISSUE THREAD

**Issue by mjskay** [mjskay/ggdist#158]
Issue with rvar and curve_interval to investigate...

---

_Originally posted by @mattansb in https://github.com/vincentarelbundock/marginaleffects/issues/539#issuecomment-1317013858_:
      
        This should also work, I think, but I'm getting an error? @mjskay, do you know what I'm doing wrong?

```R
mod <- brm(Species ~ ., 
           data = iris,
           family = categorical(), 
           backend = "cmdstanr", cores = 4)


predictions(mod, newdata = datagrid(Sepal.length = 4:5)) |>
  posteriordraws("rvar") |> 
  curve_interval(rvar, .along = c("Sepal.length", "group"))
#> Error in apply(draws, 2, halfspace_depth) : 
#>   dim(X) must have a positive length
#> In addition: Warning message:
#> Some of the variable names are missing from the model data: Sepal.length
```

**Comment by mjskay** [comment]
This should be fixed now --- let me know if there are any other issues you run into with curve_interval / rvar. Thanks!

**Comment by mattansb** [comment]
Thanks!

```R
library(brms)
library(marginaleffects)
library(ggdist)
library(ggplot2)

mod <- brm(Species ~ ., 
  data = iris,
  family = categorical(), 
  backend = "cmdstanr", cores = 4, iter = 300
)

predictions(mod, newdata = datagrid(Sepal.Width = seq(2, 4.5, len = 50))) |> 
  posteriordraws(shape = "rvar") |> 
  curve_interval(rvar, .along = c("Sepal.Width", "group")) |> 
  ggplot(aes(Sepal.Width, estimate, color = group)) + 
  facet_grid(~group) + 
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high, fill = group), 
              color = NA, alpha = 0.4) + 
  geom_line()
```

![image](https://user-images.githubusercontent.com/35330040/215262949-fae7dea5-9c2d-46e1-a5ce-72c5acb1b912.png)

**Comment by mjskay** [comment]
looks right (ish? bit of a weird model...) though to actually use the curve_interval output you'd want `rvar`, `.lower`, and `.upper` instead of `estimate`, `conf.low`, and `conf.high`

**Comment by mattansb** [comment]
Ah right.

(Yes, the model is crap - just playing around with functions 🤓)
