### ISSUE TITLE
Fill with >1 colors

### ISSUE THREAD

**Issue by arthur-albuquerque** [mjskay/ggdist#174]
Hi Matthew,

I want to fill a ggdist plot with > 1 colors. In the example below, I would like to fill in values below -1, between -1 and 0, and above 0.

How could one do it?

Thanks!

``` r
set.seed(123)

library(ggplot2)
library(ggdist)

data.frame(p = rnorm(10e4, -1, 1)) |> 
  ggplot() +
  aes(x = p, fill = after_stat(x < 0)) +
  stat_halfeye()
```

![](https://i.imgur.com/nocGT07.png)

<sup>Created on 2023-03-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mjskay** [comment]
The expression inside `after_stat()` can return anything you would normally assign to the corresponding aesthetic (`fill` in this case). So `after_stat(x < 0)` just takes advantage of the fact that `x < 0` returns a logical vector, which ggplot2 then uses to create a discrete fill color scale.

In your case you'd want an expression inside `after_stat()` that creates a factor with levels corresponding to the bins on `x` that you're looking for. The most direct way to do that is probably `cut(x, breaks = c(-Inf, -1, 0, Inf))`. Does that help?

**Comment by arthur-albuquerque** [comment]
That's perfect. This is very useful for ROPE plots. An example would be a good addition to ggdist's documentation.

Thanks!
