### ISSUE TITLE
Legend for stat_interval if multiple colors are present

### ISSUE THREAD

**Issue by qdread** [mjskay/ggdist#184]
As always thanks for your great package! 

I often want to plot `stat_interval()` with different colors for different groups in the data. To do this, I use `alpha` value to get multiple intervals stacked on top of each other, and set the `color` aesthetic to the grouping variable. My question is, in this case **how can I get a legend showing which opacity corresponds to which quantile width?**

### Example

```
library(ggplot2)
library(ggdist)

set.seed(1)

dat <- data.frame(x = c('a', 'b'), y = rnorm(1000))

ggplot(dat, aes(x = x, y = y, color = x)) +
  stat_interval(.width = c(.66, .95, .996), alpha = 1/3)
```

In addition to the legend showing which color is `a` and which color is `b`, I'd like an opacity legend showing 66%, 95%, and 99.6%. The problem is that `alpha` is hard-coded in so it isn't clear what should be mapped to the legend. If you have a solution it would be very helpful! Or if there is a different way to do this besides my "workaround" that plays better with legend, that would be great too.

**Comment by mjskay** [comment]
Yeah, you can't really create a legend for alpha automatically using intervals like this. However, you can use the `color_ramp` aesthetic that {ggdist} supplies for doing this kind of thing. Something like this:

```r
ggplot(dat, aes(x = x, y = y, color = x, color_ramp = after_stat(level))) +
    stat_interval(.width = c(.66, .95, .996)) +
    theme_ggdist()
```

![image](https://github.com/mjskay/ggdist/assets/6345019/503fbd0e-f826-4adb-aeff-5ef37d106d1a)

For more, see the [section on color ramps in the slabinterval vignette](https://mjskay.github.io/ggdist/articles/slabinterval.html#using-color-ramps-for-fill-and-color-aesthetics) or the [doc page for scale_color_ramp](https://mjskay.github.io/ggdist/reference/scale_colour_ramp.html). 

Does that help?

**Comment by qdread** [comment]
Yes that's exactly what I was looking for, should have read the docs better! Thanks! I had a slightly outdated version of ggdist installed so I needed to update to get the proper functionality.

**Comment by mjskay** [comment]
no problem, glad to help!
