### ISSUE TITLE
reverse scales on stat_pointinterval not working (working on other geoms)

### ISSUE THREAD

**Issue by jonnations** [mjskay/ggdist#185]
Maybe a bug or maybe a feature, but I can't reverse the axes when using `stat_pointinterval`. Reversing the axes works on other geoms though. I am using the dev version of `tidybayes`. Here's an example:

``` r
library(distributional)
library(tidybayes)
library(dplyr)

# Sample from docs
set.seed(1234)
df = data.frame(
  group = c("a", "b", "c"),
  value = rnorm(1500, mean = c(5, 7, 9), sd = c(1, 1.5, 1))
)
df %>%
  ggplot(aes(x = value, y = group)) +
  stat_pointinterval()
```
![image](https://github.com/mjskay/tidybayes/assets/16668795/7905a23f-dad9-46c6-8d53-54c6c0dd753f)

Reversed
```r
df %>%
  ggplot(aes(x = value, y = group)) +
  stat_pointinterval() + scale_x_reversed()

#Warning message:
#Computation failed in `stat_pointinterval()`
#Caused by error in `-x`:
#! invalid argument to unary operator 
```
![image](https://github.com/mjskay/tidybayes/assets/16668795/0fa379e8-fd50-4cc2-9297-aee4a7c6d383)

However, this works with `stat_halfeye` which (it seems?) contains a point interval

```r
df %>%
  ggplot(aes(x = value, y = group)) +
  stat_halfeye() + scale_x_reverse()
```

![image](https://github.com/mjskay/tidybayes/assets/16668795/90e47b7c-4c2b-43ad-abb6-a24895c0990b)

**Comment by mjskay** [comment]
I can't find a `scale_x_reversed()`, only a `scale_x_reverse()` (which should work...)

**Comment by jonnations** [comment]
Agg, sorry about the typo. There actually was an issue (I swear), but reinstalling both ggdist and tidybayes in a new session seems to have fixed it. Thanks.

**Comment by mjskay** [comment]
no worries, glad it's working now!
