### ISSUE TITLE
Unable to override aesthetics for legend keys

### ISSUE THREAD

**Issue by steveharoz** [mjskay/ggdist#188]
Overriding the legend key aesthetics works fine with  `geom_dotplot()`, but it doesn't work for `geom_dots()`.

```r
# points in the legend are small by default
ggplot(mtcars) + 
  aes(x=wt, fill=factor(cyl)) + 
  geom_dotplot(method = "histodot", stackgroups = TRUE)
```
![image](https://github.com/mjskay/ggdist/assets/2257540/ae4459e4-03a4-494f-b4b3-3340ddad233f)

```r
ggplot(mtcars) + 
  aes(x=wt, fill=factor(cyl)) + 
  geom_dotplot(method = "histodot", stackgroups = TRUE) + 
  # Override the point size!
  guides(fill = guide_legend(override.aes = list(size=20)))
```
![image](https://github.com/mjskay/ggdist/assets/2257540/c27ab450-ae23-4e97-a72f-5f48c09548a3)

But with `geom_dots()`, the override doesn't work.

```r
ggplot(mtcars) + 
  aes(x=wt, fill=factor(cyl), group=1) + 
  ggdist::geom_dots() + 
  # doesn't work :(
  guides(fill = guide_legend(override.aes = list(size=20)))
```

![image](https://github.com/mjskay/ggdist/assets/2257540/d5c19dbf-68d3-4e1c-9e93-ef9e0925b8a8)

Might be related to #134

**Comment by mjskay** [comment]
oh yeah, try it now on the github version, should be fixed for `geom_dots()`.

**Comment by steveharoz** [comment]
Awesome. Thanks!
