### ISSUE TITLE
Computation failed in `stat_slabinterval()`

### ISSUE THREAD

**Issue by mimisikai** [mjskay/ggdist#196]
I have a set of data that faces the problems that hit Warning message:
Computation failed in `stat_slabinterval()`
Caused by error in `bw.SJ()`:
! sample is too sparse to find TD .

 I see that #128 post probably the most similar to this problem but not work. 

Could you share some insights? 

`ggplot(df_comb, aes(x = interaction(CellType2, Status), y = percent, fill = Status)) + 
      geom_jitter(aes(color = Status), width = 0.1, alpha = 1.0, size = 1.5) +
      geom_boxplot(position = position_nudge(x = 0), width = 0.2, alpha = 0.2) +
      ggdist::stat_halfeye(aes(fill = Status), width = 0.3, justification = -0.5, alpha = 0.8, .width = 0.1, point_colour = NA, point_interval = ggdist::median_qi)`

**Comment by z3tt** [comment]
+1, same here.

**Comment by mjskay** [comment]
Ah yeah, this tends to happen on data with many duplicates in my experience. It is a result of the new bandwidth estimator in the last release, which is generally more accurate but has some corner cases where it fails. That said, whenever I have seen it fail, it is usually a sign that a density plot may not be appropriate.

In the dev version I've added a warning when those bandwidth estimators fail, and made them fall back to the more robust (but less accurate) nrd0. This warning also comes with a suggestion to try other plot types.

For example:

```r
df = data.frame(x = c(1,1,1,1,1,1,1,1.1))

df |>
  ggplot(aes(x)) +
  stat_slab()
## Warning message:
## Bandwidth calculation failed in `bandwidth_dpi()`.
## i Falling back to `bandwidth_nrd0()`.
## i This often occurs when a sample contains many duplicates, which suggests that a 
## dotplot (e.g., `geom_dots()`) or histogram (e.g., `density_histogram()` or 
## `stat_histinterval()`) may better represent the data.
## Caused by error in `bw()`:
## ! sample is too sparse to find TD 
```
![image](https://github.com/mjskay/ggdist/assets/6345019/f8587cd9-7b57-4cc7-a007-c8c75f610a7a)

and indeed those alternative charts are a more accurate representation in this case IMO; e.g.:

```r
df |>
  ggplot(aes(x)) +
  stat_slab(density = "histogram")
```
![image](https://github.com/mjskay/ggdist/assets/6345019/bb6baede-b101-48d2-890e-e9ab71f96f9b)

or:

```r
df |>
  ggplot(aes(x)) +
  geom_dots()
```
![image](https://github.com/mjskay/ggdist/assets/6345019/43a70bbc-c2ae-4fe9-8b3a-5dfdd1d079bb)
