### ISSUE TITLE
How to control the vertical axis range for discrete theoretical distributions?

### ISSUE THREAD

**Issue by isabellaghement** [mjskay/ggdist#198]
Hey Matthew, 

I am trying to plot some discrete theoretical distributions - that is, Poisson and Binomial(n,p) with n = 1 - but the vertical axis for my plots looks monstrously out of range, dropping below 0.  

It probably would be better if by default the tiles were NOT centered around each of the discrete values?  This way, the tile centered at 0 would NOT drop below 0.

![image](https://github.com/mjskay/ggdist/assets/57458528/153fa4a3-5541-4043-8689-73e8da73514d)

Not sure how to fix this to get something more sensibly looking? Any ideas for how to proceed would be greatly appreciated.  Maybe it's just a matter of removing vertical axis labelling for values below 0? 

Dropping my R code here in case it comes in handy:

```
library(distributional)
library(ggdist)
library(tibble)
library(ggplot2)
library(patchwork)
library(ggeasy)
library(magrittr)

theme_set(theme_bw())


Plot1 <- 
  tibble(
    group = c("A","B"),
    mu = c(10, 20), 
    sigma = c(2, 2)
  ) %>%
  ggplot(aes(x = group, fill = group)) +
  stat_slab(aes(ydist = dist_normal(mu, sigma))) +
  geom_point(aes(y = mu), size = 3.5) + 
  geom_line(aes(y = mu, group = NA), 
            linewidth = 1, linetype = 2,  
            colour = "darkorange") +
  scale_fill_brewer() + 
  xlab("Population") + 
  ylab("Normal Response Distribution") +
  labs(title = "Compare Means of Two Populations") 
Plot1

Plot2 <- 
  tibble(
    group = c("A","B"),
    lambda = c(2, 4)
  ) %>%
  ggplot(aes(x = group, fill = group)) +
  stat_slab(aes(ydist = dist_poisson(lambda)), 
            outline_bars = TRUE, 
            colour = "white") +
  geom_point(aes(y = lambda), size = 3.5) + 
  geom_line(aes(y = lambda, group = NA), 
            linewidth = 1, linetype = 2,  
            colour = "darkorange") +
  scale_fill_brewer() + 
  xlab("Population") + 
  ylab("Poisson Response Distribution") +
  labs(title = "Compare Means of Two Populations") 
Plot2


Plot3 <- 
  tibble(
    group = c("A","B"),
    size = c(1, 1),
    prob = c(0.2, 0.6)
  ) %>%
  ggplot(aes(x = group, fill = group)) +
  stat_slab(aes(ydist = dist_binomial(size, prob)), 
            outline_bars = TRUE, 
            colour = "white") +
  geom_point(aes(y = size * prob), size = 3.5) + 
  geom_line(aes(y = size * prob, group = NA), 
            linewidth = 1, linetype = 2,  
            colour = "darkorange") +
  scale_fill_brewer() + 
  xlab("Population") + 
  ylab("Binomial Response Distribution") +
  labs(title = "Compare Means of Two Populations") 
Plot3

Plot <- 
  Plot1 + 
  Plot2 + 
  Plot3 +
  plot_layout(ncol = 3) & 
  easy_remove_legend()

Plot

```

Thank you very much! 

Isabella 

P.S. I managed to get something like this going for the right-most plot: 

![image](https://github.com/mjskay/ggdist/assets/57458528/3bc99dbe-4f93-4649-bf40-cb9df1f18794)

using this R code for it: 

`
Plot3 <- 
  tibble(
    group = c("A","B"),
    size = c(1, 1),
    prob = c(0.2, 0.6)
  ) %>%
  ggplot(aes(x = group, fill = group)) +
  stat_slab(aes(ydist = dist_binomial(size, prob)), 
            outline_bars = TRUE, 
            colour = "white") +
  geom_point(aes(y = size * prob), size = 3.5) + 
  geom_line(aes(y = size * prob, group = NA), 
            linewidth = 1, linetype = 2,  
            colour = "darkorange") +
  scale_fill_brewer() + 
  xlab("Population") + 
  ylab("Bernoulli Response Distribution") +
  scale_y_continuous(breaks = c(-0.5, 0, 0.5, 1, 1.5), 
                     labels = c("", 0, "", 1, ""))
  
Plot3
`
But it still looks rough around the edges.

**Comment by mjskay** [comment]
I would use `scale_y_continuous(breaks = c(0,1), minor_breaks = NULL)`:

```r
tibble(
    group = c("A","B"),
    size = c(1, 1),
    prob = c(0.2, 0.6)
) %>%
    ggplot(aes(x = group, fill = group)) +
    stat_slab(aes(ydist = dist_binomial(size, prob)),
        outline_bars = TRUE,
        colour = "white") +
    geom_point(aes(y = size * prob), size = 3.5) +
    geom_line(aes(y = size * prob, group = NA),
        linewidth = 1, linetype = 2,
        colour = "darkorange") +
    scale_fill_brewer() +
    xlab("Population") +
    ylab("Bernoulli Response Distribution") +
    scale_y_continuous(breaks = c(0,1), minor_breaks = NULL)
```
![image](https://github.com/mjskay/ggdist/assets/6345019/0616f602-95c2-47fe-8660-41b06ead405c)

**Comment by isabellaghement** [comment]
Awesome!  Such a simple fix.  Thanks so much, Matthew, and have a lovely weekend.

**Comment by mjskay** [comment]
No problem, you too!
