### ISSUE TITLE
parse_dist() and lower bounds for class = sd

### ISSUE THREAD

**Issue by ASKurz** [mjskay/ggdist#20]
Hey @mjskay,

I wanted to use `parse_dist()` and `stat_dist_halfeye()` to compare two priors for a hierarchical $\sigma$ parameter. They were Exponential(1) and half-Normal(0, 1). With **brms**, the default behavior sets the lower bounds for both to zero. However, my **tidybayes** workflow did not set the lower bound for the half-Normal. E.g., try this:

```
library(brms)
library(tidybayes)
library(tidyverse)

c(prior(exponential(1), class = sd),
  prior(normal(0, 1), class = sd)) %>% 
  parse_dist(prior) %>% 
  
  ggplot(aes(y = prior, dist = .dist, args = .args)) +
  stat_dist_halfeye(.width = .95)
```

Attempting to manually set the lower bound with `prior(normal(0, 1), class = sd, lb = 0)` won't work, either. You get a warning message, instead: `Error: Currently boundaries are only allowed for classe(s) 'b'.`. Is there an easy fix?

**Comment by mjskay** [comment]
Yeah there is not a great workflow for this yet. The simplest workaround I've come up with is to use the "trunc" distribution family from {truncdist}. See `?truncdist::dtrunc` --- basically it is way to create truncated distributions from existing distirbution families in R, where the first argument is the distribution name, second is lower bound, and third is upper bound. Then the remaining arguments are passed to the underlying distribution.

The nice thing is this works with how ggdist uses distribution argument aesthetics pretty easily --- basically instead of passing the distribution name to `dist` aesthetic, you pass `"trunc"` to the `dist` aesthetic and the distribution name to the `arg1` aesthetic. Then lower and upper bounds go to `arg2` and `arg3`, and the remaining arguments go to `args` and everything should line up with how `dtrunc` expects its arguments to be:

```r
library(truncdist)
library(brms)
library(ggdist)   # or library(tidybayes)
library(tidyverse)

c(prior(exponential(1), class = sd),
  prior(normal(0, 1), class = sd)) %>% 
  parse_dist(prior) %>%

  ggplot(aes(y = prior, dist = "trunc", arg1 = .dist, arg2 = 0, arg3 = Inf, args = .args)) +
  stat_dist_halfeye()
```
![image](https://user-images.githubusercontent.com/6345019/86287601-733c6000-bbb6-11ea-8349-f3fec40cb84f.png)

Once https://github.com/mjskay/ggdist/issues/14 is done I want to come up with a better workflow for brms priors using distribution objects from {distributional} which should hopefully make stuff like this more straightforward. Hopefully this workaround is pretty okay for the meantime.

**Comment by ASKurz** [comment]
Thanks @mjskay. This looks like a nice temporary workaround. Since it looks like the issue might be resolved as a special case of a broader workflow change, it seems like we can close this issue.

**Comment by ASKurz** [comment]
Hey @mjskay, is this still the recommended workflow for truncated distributions? My current use case is to plot $\operatorname{Exponential}(1 / 4.309458)$, with an upper bound of 10. Here's my workflow:

```{r}
library(truncdist)
library(brms)
library(ggdist)   # or library(tidybayes)
library(tidyverse)

# 1 / 4.309458 is about 0.2320477
prior(exponential(0.2320477), class = sigma, ub = 10) %>% 
  parse_dist() %>% 
  
  ggplot(aes(y = 0, dist = "trunc", arg1 = .dist, arg2 = 0, arg3 = 10, arg4 = 1 / 4.309458, args = .args)) +
  stat_halfeye() +
  geom_vline(xintercept = 10, linetype = 2)+
  labs(title = "Exponential(1 / 4.309458), truncated at 10",
       x = NULL) +
  coord_cartesian(xlim = c(0, 20))
```
<img width="735" alt="Screen Shot 2023-02-01 at 11 51 22 AM" src="https://user-images.githubusercontent.com/19917004/216123160-6231a93e-b670-4dc3-84db-527aa6ccb4b1.png">

**Comment by mjskay** [comment]
Ah right, I did promise to come up with a better workflow once distributional support was added, thanks for reminding me :).

I just added an attempt at such a workflow on the `dev` branch if you want to test it via `remotes::install_github("mjskay/ggdist@dev")`. Basically, in addition to the existing `.dist` and `.args` columns, `parse_dist()` now generates a `.dist_obj` column containing a {distributional} object representing the distribution. If the `lb` and `ub` columns are present (as in output from `brms::prior()`), this object will also have the appropriate truncation applied to it using `dist_truncated()`.

This should make sd parameters much easier to visualize:

``` r
library(distributional)
library(ggdist) # remotes::install_github("mjskay/ggdist@dev")
library(ggplot2)
library(brms)

c(
  prior(exponential(0.2320477), class = sigma, ub = 10), 
  prior(normal(0,4), class = sd, lb = 0)
) |>
  parse_dist() |> 
  ggplot(aes(xdist = .dist_obj, y = format(.dist_obj))) + 
  stat_halfeye()
```

![](https://i.imgur.com/07kpyNF.png)

Does that help?

**Comment by ASKurz** [comment]
Overall I like it @mjskay, but there are two points to consider. Notice how the y-axis label suggests there is no lower bound for the exponential prior, even though there is a definitional bound at 0. Also, it's not totally clear with the pic you uploaded, but if you look closely, you'll see that the point at which the exponential density gets truncated at 10 is slightly slanted. Here's a zoomed in version of the pic from my computer:

<img width="141" alt="Screen Shot 2023-02-01 at 2 43 36 PM" src="https://user-images.githubusercontent.com/19917004/216159034-79c13074-036f-48d1-9af5-4c67b0f5aa93.png">

The slant seems odd.

**Comment by mjskay** [comment]
The name just comes from what `format()` outputs for `dist_truncated()`: there's no left truncation so the lower bound is `-Inf`. You could set lb = 0 on that prior if you want that to be different.

The slant is a byproduct of needing to define a grid to draw the density over. If you increase the `n` argument to `stat_halfeye()` the grid will be finer and the slant less noticeable.

**Comment by ASKurz** [comment]
I see. Okay, that works. Thanks!

For posterity, here's the update with your recommendations:

```
c(
  prior(exponential(0.2320477), class = sigma, lb = 0, ub = 10), 
  prior(normal(0,4), class = sd, lb = 0)
) |>
  parse_dist() |> 
  ggplot(aes(xdist = .dist_obj, y = format(.dist_obj))) + 
  stat_halfeye(n = 1e4)
```
<img width="873" alt="Screen Shot 2023-02-02 at 9 40 59 AM" src="https://user-images.githubusercontent.com/19917004/216370756-26798ef3-e2fc-405d-b691-a97f23c0d683.png">

**Comment by ASKurz** [comment]
Hey @mjskay, one last follow-up (*last*, he says...). Would you recommend the `xdist = .dist_obj, y = format(.dist_obj)` style syntax as a general approach, now? For example, I just ran across a use case where I wanted to plot some default `brm()` priors

$$
\begin{align}
\beta_0 & \sim \operatorname{Student-t}(3, 49.5, 3.6) \\
\sigma & \sim \operatorname{Student-t}^+(3, 0, 3.6).
\end{align}
$$

I used the code

```{r}
c(prior(student_t(3, 49.5, 3.6)),
  prior(student_t(3, 0, 3.6), class = sigma, lb = 0)) %>% 
  parse_dist() %>% 
  
  ggplot(aes(xdist = .dist_obj, y = format(.dist_obj))) + 
  stat_halfeye()
```

<img width="863" alt="Screen Shot 2023-03-12 at 3 57 20 PM" src="https://user-images.githubusercontent.com/19917004/224573241-d7dab784-5df2-402e-b8d8-cba3a3852c77.png">


It worked great. Are there contexts where the other `dist = .dist, args = .args` type snytax would be more appropriate?

**Comment by mjskay** [comment]
Yeah, in general the `.dist_obj` object should be the preferred thing to use going forward. The `dist` and `args` aesthetics aren't going anywhere for backwards compatibility, but the object-based representation is just easier to pass around I think.

Also, really glad it's working well!! :)

**Comment by ASKurz** [comment]
Cool. I'm teaching a beginner's workshop a week from now and that's the approach I'll show them, then.
