### ISSUE TITLE
Missing .RProj file

### ISSUE THREAD

**Issue by steveharoz** [mjskay/ggdist#200]
The RStudio project file (.RProj) seems to be missing. `.gitignore` seems to have blocked it. Including it would help with contributing!

**Comment by mjskay** [comment]
Oh yeah good point, I disabled that years ago because I didn't like the idea of putting IDE-specific things in the repo. But since so many people use it (and it means I can set tab settings for folks who want to contribute) it probably makes sense to restore it.
