### ISSUE TITLE
Add ability to "mark" different `at` values in `stat_spike()`

### ISSUE THREAD

**Issue by mattansb** [mjskay/ggdist#203]
As far as I can tell, it is currently is not easy possible to color (or otherwise change the spike's aesthetics) each "skipe" (as defined by the `at` argument).

``` r
library(ggplot2)
library(ggdist)
library(distributional)

toy_data <- data.frame(
  dist = dist_student_t(c(3, 20), 0, 10),
  label = c("t(3, 0, 10)", "t(20, 0, 10)")
)

at_funs <- list(
  five = 5, 
  median = median,
  qi = qi
)

ggplot(toy_data, aes(y = label, xdist = dist)) + 
  stat_slabinterval() + 
  stat_spike(at = at_funs) + 
  scale_thickness_shared()
```

![](https://i.imgur.com/XC7WCry.png)

If I want to color those spikes I can either add them one by one:

``` r
ggplot(toy_data, aes(y = label, xdist = dist)) + 
  stat_slabinterval() + 
  stat_spike(aes(color = "five"), at = at_funs[["five"]]) + 
  stat_spike(aes(color = "median"), at = at_funs[["median"]]) + 
  stat_spike(aes(color = "qi"), at = at_funs[["qi"]]) + 
  scale_thickness_shared()
```

![](https://i.imgur.com/CS3MVwA.png)

It would be great if the list names (or something else?) coul be one of the “computed” variables, so that `after_stat()` could be used.
(Like this, but not ugly)

``` r
ggplot(toy_data, aes(y = label, xdist = dist)) + 
  stat_slabinterval() + 
  stat_spike(aes(color = after_stat(factor(rep(c(1, 2, 3, 3), times = 2)))), 
             at = at_funs) + 
  scale_thickness_shared()
```

![](https://i.imgur.com/t9FGkGM.png)

<sup>Created on 2023-11-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Ideally, if the `at` is a named list or vector, the names would be used. Else, some generic 1:n can also be used.

Thanks!

**Comment by mjskay** [comment]
oh yeah, you could do a workaround here using lapply or mapply/pmap to produce layers, but the idea of yielding `at` as a computed variable is a much nicer solution :).

**Comment by mjskay** [comment]
on `dev` branch now if you want to kick the tires:

```r
data.frame(d = distributional::dist_gamma(2,2)) |> 
  ggplot(aes(xdist = d)) + 
  stat_slab(fill = "gray90") + 
  stat_spike(aes(color = after_stat(at)), at = c("mean", "median", mode = "Mode", "qi")) + 
  theme_ggdist()
```
![image](https://github.com/mjskay/ggdist/assets/6345019/530b9c4b-4339-4341-854b-fcf0dcc6d1b1)

**Comment by mattansb** [comment]
Thanks @mjskay ! I did find one issue (:

``` r
library(ggplot2)
library(ggdist) # dev
library(distributional)

toy_data <- data.frame(
  dist = dist_student_t(c(3, 20), 0, 10),
  label = c("t(3, 0, 10)", "t(20, 0, 10)")
)
```

This works as expected

``` r
at_funs <- list(
  5, 
  Md = median,
  "qi"
)

ggplot(toy_data, aes(y = label, xdist = dist)) + 
  stat_spike(aes(color = after_stat(at)), at = at_funs)
```

![](https://i.imgur.com/DKXyf7T.png)

But functions (not function names) as unnamed list elements are all given the same “at” - `<fn>`:

``` r
at_funs <- list(
  5, 
  median,
  qi
)

ggplot(toy_data, aes(y = label, xdist = dist)) + 
  stat_spike(aes(color = after_stat(at)), at = at_funs)
```

![](https://i.imgur.com/lQHmcuQ.png)

Maybe functions as unnamed list elements should be serialized? `<fn1>`, `<fn2>`, etc..?

<sup>Created on 2023-12-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mjskay** [comment]
Yeah good point, the naming logic was not particularly robust here anyway so I factored it out and rewrote it. Should be much better now; let me know!

**Comment by mattansb** [comment]
Yup, that works beautifully! Also allows for "matching" `at` values by giving them the same name.

Thanks!

``` r
library(ggplot2)
library(ggdist) # dev
library(distributional)

toy_data <- data.frame(
  dist = dist_chisq(c(3, 20)),
  label = c("chisq(3)", "chisq(20)")
)

at_funs <- list(
  df = c(3, 20),
  d = Mode,
  d = hdci,
  qi = median,
  "qi"
)

ggplot(toy_data, aes(y = label, xdist = dist)) + 
  stat_slab(fill = "grey80") + 
  stat_spike(aes(color = after_stat(at)), at = at_funs)
```

![](https://i.imgur.com/k26xrke.png)

<sup>Created on 2023-12-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mattansb** [comment]
Thanks!
