### ISSUE TITLE
Strange `stat_gradientinterval()` behavior when rendering quarto doc to html

### ISSUE THREAD

**Issue by markjrieke** [mjskay/ggdist#204]
I'm not 100% sure if this is an issue with ggdist, the graphics device, or quarto, but worth putting on your radar. 

I ran into some strange behavior when rendering a html doc that makes use of `stat_gradientinterval()`. If I explicitly call `library(ggdist)` in the doc, the gradients are rendered as expected:

```
---
title: "temp"
format: html
knitr:
  opts_chunk: 
    dev: "ragg_png"
---

```{r}
library(tidyverse)
library(ggdist)

tibble(a = rnorm(1e4, 0.01, 0.0001),
       b = rnorm(1e4, 0.02, 0.0002)) %>%
  pivot_longer(everything(),
               names_to = "arm_name",
               values_to = "estimate") %>%
  ggplot(aes(x = estimate,
             y = arm_name)) + 
  stat_gradientinterval()
```

<img width="674" alt="image" src="https://github.com/mjskay/ggdist/assets/31866288/6f4cdcad-2424-4ee5-9beb-4f88fc7397df">

However, if I call the function with `ggdist::stat_gradientinterval()`, I get this weird block-y image:

```
---
title: "temp"
format: html
knitr:
  opts_chunk: 
    dev: "ragg_png"
---

```{r}
library(tidyverse)

tibble(a = rnorm(1e4, 0.01, 0.0001),
       b = rnorm(1e4, 0.02, 0.0002)) %>%
  pivot_longer(everything(),
               names_to = "arm_name",
               values_to = "estimate") %>%
  ggplot(aes(x = estimate,
             y = arm_name)) + 
  ggdist::stat_gradientinterval()
```
<img width="681" alt="image" src="https://github.com/mjskay/ggdist/assets/31866288/0c45b4ca-728e-4bfd-97fc-a75eb11640b2">

The workaround of specifically attaching the package works, but ideally it'd work with either method. From a cursory glance through the package code, I didn't see any calls to on attach/on load in the package, so really a head-scratcher. 

Thanks again for the package, it's a real viz rockstar

**Comment by mjskay** [comment]
Huh, that is indeed perplexing. I'll take a look.

Quick question: are you running on the latest R, latest quarto, and with all packages up to date? (that at least narrows my search...)

**Comment by mjskay** [comment]
Nevermind, I found the problem. It's not picking up the default scale for the `slab_alpha` aesthetic, which is a bit odd (I believe there's a mechanism so that it should be able to find it, but maybe I messed something up there). You can fix it by adding `ggdist::scale_slab_alpha_continuous()` to the plot manually. I'll see if I can fix it so you don't have to.

**Comment by mjskay** [comment]
Yeah, this is the correct workaround until https://github.com/tidyverse/ggplot2/pull/4799 is fixed --- add the scale manually.

**Comment by markjrieke** [comment]
awesome --- thank you for checking!
