### ISSUE TITLE
arrows on point_intervals

### ISSUE THREAD

**Issue by ASKurz** [mjskay/ggdist#206]
I see you have added the `arrow` argument to `geom_spike()`. It would be really cool if you added the `arrow` option for point_intervals in other functions, such as `stat_halfeye()` and so on, so the ends of the point_intervals could be arrows.

**Comment by mjskay** [comment]
Hmm I suppose in principle I'm not opposed. It would also be one way for people to put the little vertical markers on the intervals that some people like using `grid::arrow(angle = 90,ends = "both")`.

**Comment by mjskay** [comment]
Should work on the github version now:

```r
library(ggplot2)
library(ggdist)
library(distributional)

ggplot() + 
  stat_slabinterval(
    aes(xdist = dist_normal(0,1)),
    arrow = arrow(angle = 90, length = unit(4, "pt"), ends = "both")
  )
```
![image](https://github.com/mjskay/ggdist/assets/6345019/d25d5ce2-5642-4e4f-bba1-49220c793f17)

**Comment by ASKurz** [comment]
I love it!
