### ISSUE TITLE
Slab outline colour by group

### ISSUE THREAD

**Issue by Patlane** [mjskay/ggdist#212]
Hello,

I would like to change the slab outline colour by group. In my case just adding ´´´scale_slab_color_*´´´ to my plot prompt does not work. I saw in this post [https://stackoverflow.com/questions/69144667/scale-interval-color-discrete-doesnt-work-in-ggdist](url). For the stat_pointinterval() you exploy the internally generated stat(level) variable. I already tried this, it doesn't work for the slab outline color. Could somebody help me out, please. My plotting code is below:
```
draws_load %>% 
  pivot_longer(cols = variables(.), names_to = c("Length", "Load"), names_sep="_", values_to = 'draws') %>%
  mutate(Length = factor(Length),
         Load = factor(Load)) %>%
  mutate(Length = fct_relevel(Length, "Short", "Long"),
         Load = fct_relevel(Load, "Low", "High")) %>%
  ggplot(aes(y = draws, x= Load, fill = Length)) +
  scale_fill_manual(values = c( "#FFC300","#A5AB52"))+
  scale_shape_manual(values = c(21, 22))+
  stat_halfeye(slab_alpha=6, position = "dodgejust", point_size = 4, aes(shape=Length))
```
Thanks a lot!

**Comment by mjskay** [comment]
Hmm I'm not sure I follow - could you say more about what you want the outline color to be, or provide data with code so that I can execute it? Thanks!

**Comment by Patlane** [comment]
Hi, thanks for asking back. I have modified the code. The plotting code does not work now, but you should see from the one of half last rows what I am trying to do but can't get hang of it: " slab_color=Length))+
  scale_slab_color_*(values = c( "#E3A80F", "darkgreen"))"

Thanks for helping
```
library(tibble)

# Number of iterations and draws
num_iterations <- 100
num_draws <- 160

# Generate data frame
data_frame <- tibble(
  Length = rep(rep(c('Short', 'Long'), each = num_draws / 2), times = num_iterations / 2),
  Load = rep(rep(c('Low', 'High'), each = num_draws / 2), times = num_iterations/2),
  draws = rnorm(num_iterations/2 * num_draws, mean = c(1.93, 1.66, 1.98, 1.88), sd = 0.1)
)

# Print the first few rows
head(data_frame)

data_frame %>%
  ggplot(aes(y = draws, x= Load, fill = Length)) +
  scale_fill_manual(values = c( "#FFC300","#A5AB52"))+
  scale_shape_manual(values = c(21, 22))+
  stat_halfeye(slab_alpha=6, position = "dodgejust", point_size = 4, aes(shape=Length, slab_color=Length))+
  scale_slab_color_*(values = c( "#E3A80F", "darkgreen"))
```

**Comment by mjskay** [comment]
Ah, now I understand.

To use the base ggplot color scales with the sub-geometry aesthetics like `slab_color`, `slab_fill`, etc, you can pass the aesthetic name to the `aesthetics` parameter of the scale function, something like: `scale_color_manual(values = c( "#E3A80F", "darkgreen"), aesthetics = "slab_color")`.

That does this:

```r
data_frame %>%
  ggplot(aes(y = draws, x= Load, fill = Length)) +
  scale_fill_manual(values = c( "#FFC300","#A5AB52"))+
  scale_shape_manual(values = c(21, 22))+
  stat_halfeye(slab_alpha=6, position = "dodgejust", point_size = 4, aes(shape=Length, slab_color=Length)) +
  scale_color_manual(values = c( "#E3A80F", "darkgreen"), aesthetics = "slab_color")
```
![image](https://github.com/mjskay/ggdist/assets/6345019/0b5d5bd8-d0e3-4286-b827-72651d91ea99)

The other solution, if sub-geometry aesthetics (like `slab_color`) are not playing nice with base ggplot scales (this can happen), it may be easier to decompose `stat_halfeye()` into a `stat_slab()` and a `stat_pointinterval()`. Then can make it easier to specify what aesthetics go with what, and you don't need to use `slab_color` for the slab outline, you can just use `color`:

```r
data_frame %>%
  ggplot(aes(y = draws, x= Load, fill = Length)) +
  scale_fill_manual(values = c( "#FFC300","#A5AB52"))+
  scale_shape_manual(values = c(21, 22))+
  stat_slab(position = "dodgejust", aes(color = Length)) +
  stat_pointinterval(position = "dodgejust", point_size = 4, aes(shape = Length)) +
  scale_color_manual(values = c( "#E3A80F", "darkgreen"))
```
![image](https://github.com/mjskay/ggdist/assets/6345019/a0ad2386-3816-4947-b167-75ffc7e5645f)
