### ISSUE TITLE
Empty space above stat_slabinterval

### ISSUE THREAD

**Issue by TeemuSailynoja** [mjskay/ggdist#216]
Suppose I want to make a simple KDE density plot with a dot interval at the bottom using `stat_slabinterval`. For some reason, perhaps overlaying other geoms, I want the density values on the y-axis to be non-normalized and unscaled, so I do the following:

```R
set.seed(10)
df <- data.frame(x = rnorm(100))
ggplot(df, aes(x = x)) +
    stat_slabinterval(normalize = "none", scale = 1)
```
The resulting plot has a lot of empty space above the density:

![image](https://github.com/mjskay/ggdist/assets/33978952/8d4a02ea-5127-4b23-9d37-44772a8c5228)

When I add `+ ylim(c(0,.5))` to remove the empty space, the whole KDE gets removed:

## Using `ylim`
```R
ggplot(df, aes(x = x)) + 
    stat_slabinterval(normalize = "none", scale = 1) + ylim(c(0, .5))
Warning message:
Removed 501 rows containing non-finite outside the scale range (`geom_slabinterval()`).
``` 
![image](https://github.com/mjskay/ggdist/assets/33978952/d48e2441-6e61-44fd-988d-6fe893e203af)

## Using `height`
Reading the documentation, I come to the conclusion, that `height` should affect the maximum height of the density:
  
![image](https://mjskay.github.io/ggdist/articles/slabinterval_files/figure-html/slabinterval_components-1.png)

But something unexpected happens:
```R
ggplot(aes(x = x)) + 
    stat_slabinterval(normalize = "none", scale = 1, height = .5)
```
![image](https://github.com/mjskay/ggdist/assets/33978952/90c0bdf1-34a2-4fa9-9ca8-82853f0cf46b)

Now the `normalize = "none"` doesn't seem to be in effect?

How should I approach removing this empty space?

**Comment by mjskay** [comment]
In ggplot2 you should (almost always) use coord_cartesian(ylim =...) instead of ylim(...), as ylim removes data. In this case the slab has an invisible bounding box used to preserve its spacing that causes it to be removed by ylim(), but coord_cartesian should work.

**Comment by TeemuSailynoja** [comment]
Thank you!
Using `coord_cartesian` did what I wanted. For more automatically limiting the invisible bounding box to what I wanted, after more careful investigation of the documentation, I came up with:

```R
options("ggdist.experimental.slab_data_in_intervals" = TRUE)
set.seed(10)
df <- data.frame(x = rnorm(100))

ggplot(df, aes(x = x)) +
    stat_slabinterval(aes(height = max(after_stat(pdf))), scale = 1)
```
![image](https://github.com/mjskay/ggdist/assets/33978952/0103129f-2e89-45a8-bdad-11aca0ac4db1)

**Comment by mjskay** [comment]
Ah great!
