### ISSUE TITLE
`trim` not working when passed directly to density function

### ISSUE THREAD

**Issue by fkohrt** [mjskay/ggdist#220]
I believe the following examples are supposed to lead identical results, but they don't:

```r
faithful |>
  ggplot2::ggplot(ggplot2::aes(x = eruptions)) +
  ggdist::stat_slab(
    density = ggdist::density_bounded(trim = FALSE),
    color = "black"
  )
```

![](https://github.com/mjskay/ggdist/assets/12914806/508d910f-8f77-4305-9488-cd7b2713d09a)

```r
faithful |>
  ggplot2::ggplot(ggplot2::aes(x = eruptions)) +
  ggdist::stat_slab(
    density = ggdist::density_bounded(),
    trim = FALSE,
    color = "black"
  )
```

![](https://github.com/mjskay/ggdist/assets/12914806/7691287b-3e0d-429e-9fb0-44dd2cfd7d3b)

- R version 4.3.3 (2024-02-29)
- ggdist 3.3.2

**Comment by fkohrt** [comment]
I believe the same is true for the argument `n`, e.g. compare the following two examples:

As argument to `stat_slab()` (working):

```r
data.frame(x = rcauchy(10000)) |>
  ggplot2::ggplot(ggplot2::aes(x = x)) +
  ggdist::stat_slab(n = 2^16) +
  ggplot2::coord_cartesian(xlim = c(-10, 10))
```

As argument to `density_unbounded()` (not working):

```r
data.frame(x = rcauchy(10000)) |>
  ggplot2::ggplot(ggplot2::aes(x = x)) +
  ggdist::stat_slab(density = ggdist::density_unbounded(n = 2^16)) +
  ggplot2::coord_cartesian(xlim = c(-10, 10))
```

**Comment by mjskay** [comment]
Yup --- these arguments (and a few others) should have `waiver()`s in `stat_slabinterval()`. Should be fixed on master now. Thanks for the report!
