### ISSUE TITLE
A way to specify defaults for subguide, subsccale and normalize?

### ISSUE THREAD

**Issue by venpopov** [mjskay/ggdist#225]
Thanks for solving #219. I'm trying to come up with a easier to way to write all of this:

```r
data.frame(prior = c("student_t(3,2,0.75)", "normal(0,5)")) %>% 
  parse_dist(prior) %>% 
  ggplot(aes(xdist = .dist_obj)) +
  stat_slab(fill = NA, color = "red",
            subguide = subguide_outside(title = "density"),
            subscale = subscale_thickness(expand = expansion(c(0, 0.05))),
            normalize = 'groups') +
  facet_wrap(~prior, scales = "free") +
  ggdist::theme_ggdist() +
  theme(plot.margin = margin(5.5, 5.5, 5.5, 50),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          axis.title.y = element_blank())
```

I like this format where the y scale is completely replaced by the thickness scale as it looks more like what I would get from normal use of ggplot2, but I don't want to type all of that, and I would like to also define defaults for our package. Some of the things above I can of course extract into a custom theme:

```r
theme_dist <- function() {
  ggdist::theme_ggdist() +
    theme(plot.margin = margin(5.5, 5.5, 5.5, 50),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          axis.title.y = element_blank())
}
```

leading to the more compact:

```r
data.frame(prior = c("student_t(3,2,0.75)", "normal(0,5)")) %>% 
  parse_dist(prior) %>% 
  ggplot(aes(xdist = .dist_obj)) +
  stat_slab(fill = NA, color = "red",
            subguide = subguide_outside(title = "density"),
            subscale = subscale_thickness(expand = expansion(c(0, 0.05))),
            normalize = 'groups') +
  facet_wrap(~prior, scales = "free") +
  theme_dist()
```

but I haven't figure out a way to define the subguide, subscale and normalize arguments to use the above settings by default. Of course, I could make a wrapper for stat_slab:

```r
stat_slab2 <- function(..., 
  subguide = subguide_outside(title = "density"),
  subscale = subscale_thickness(expand = expansion(c(0, 0.05))),
  normalize = 'groups') {
  
  stat_slab(..., subguide = subguide, subscale = subscale, normalize = normalize)
}
```

allowing me to use

```r
data.frame(prior = c("student_t(3,2,0.75)", "normal(0,5)")) %>% 
  parse_dist(prior) %>% 
  ggplot(aes(xdist = .dist_obj)) +
  stat_slab2(fill = NA, color = 'red') +
  facet_wrap(~prior, scales = "free") +
  theme_dist()
```

but I was wondering if there's a way to specify those arguments without making a wrapper function?

(in practice we are making an autoplot() function, for which this doesn't matter, but for myself I want to leave the option for more control while still using defaults I like)

**Comment by mjskay** [comment]
Hmm yeah. If I was doing this I would probably either define a custom function like you have, or at least save a subguide and subscale for reuse, like:

```r
sg = subguide_outside(title = "density")
sc = subscale_thickness(expand = expansion(c(0, 0.05)))

# later  ..
stat_slab(subscale = sc, subguide = sg)
```

But I can see the value of setting at least subguides and subscales globally. Fortunately the function search path for string suffixes passed to those functions already uses the global environment. This made it easy to implement a version of what base ggplot does to allow scale defaults to be set. ggplot lets you set default scales by creating a function with the same name as the default (e.g. `scale_x_continuous = ...`), and I've implemented something similar with subguides and subscales. 

You can now set `subscale_thickness`, `subguide_slab`, `subguide_dots`, and `subguide_spike` to change the corresponding defaults; e.g.:

```r
theme_set(
  ggdist::theme_ggdist() +
  theme(plot.margin = margin(5.5, 5.5, 5.5, 50),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          axis.title.y = element_blank())
)

# need `ggdist::` for to prevent infinite recursion here
subscale_thickness = ggdist::subscale_thickness(expand = expansion(c(0, 0.05)))
# need theme = theme_ggdist() because otherwise the guide uses the default
# axis theme elements, which are set to blank above
subguide_slab = ggdist::subguide_outside(title = "density", theme = theme_ggdist())

data.frame(prior = c("student_t(3,2,0.75)", "normal(0,5)")) |>
  parse_dist(prior) |>
  ggplot(aes(xdist = .dist_obj)) +
  stat_slab(fill = NA, color = "red", normalize = "groups") +
  facet_wrap(~prior, scales = "free")
```
![image](https://github.com/mjskay/ggdist/assets/6345019/b941d931-4dcb-40b5-b4da-83002b50168f)

I don't think I will provide a similar mechanism for `normalize` (or per #223, `subscale_by`), for several reasons: (1) it's not a lengthy parameter, (2) it's not a theme-related parameter (so it feels less sensible to modify it at a global level --- too much potential to break others' code), and (3) I think at that point it would be better to have a generic mechanism for updating geom/stat parameters, which would be more of a ggplot2-level thing. TBH you probably already could do that by just modifying the `$default_params` list of a geom object (similar to what `ggplot2::update_geom_defaults()` does for setting default aesthetic mappings). However, I don't really recommend this, as it has too much potential to break other people's code.

**Comment by venpopov** [comment]
Thanks, this works. Ideally it would have been nice to be able to setup that from the theme, but I see your point that this is a ggplot issue, not a ggdist issue. I can set these as global variables from the theme function, but that's not good practice, just like I agree without you that alterin default aestatics can break others code. So I might just go with the wrapper function for stat_slab, which seems the cleanest solution
