### ISSUE TITLE
Adjust position of points/intervals on the density axis.

### ISSUE THREAD

**Issue by bwiernik** [mjskay/ggdist#27]
I'm trying to plot two interval distributions side-by-side (to show group overlap). I'd like to be able to adjust the position of the summary points/intervals so that they don't overlap each other, but I can't see a way to do that (e.g., to move one group's summary statistics up on the y-axis when the variable values are on the x-axis). Could something like `point_offset` and `interval_offset` parameters be added?

**Comment by wzel** [comment]
`position = "dodge"` works for me, even though it does not let you specify the distances. Check the "Slab + interval stats and geoms" vignette for examples.

**Comment by bwiernik** [comment]
Thanks for the idea. That helped me to realize I could accomplish this by specifying the slap and the interval as separate stats:
```
set.seed(1234)
df <- tribble(
    ~group, ~subgroup, ~value,
    "a",          "h", rnorm(1000, mean = 5),
    "b",          "h", rnorm(1000, mean = 7, sd = 1.5),
    "c",          "h", rnorm(1000, mean = 8),
    "c",          "i", rnorm(1000, mean = 9),
    "c",          "j", rnorm(1000, mean = 7)
  ) %>%
  unnest(value)
df %>%
    ggplot(aes(fill = group, color = group, x = value)) +
    stat_halfeye(point_interval = NULL, alpha = .3) +
    stat_pointinterval(position = position_dodge(width = .1, preserve = "single")) +
    ggtitle("stat_eye()") + theme_minimal()
```

Might be nice to have the interval parameters be separately modifiable in the combined stats.

**Comment by mjskay** [comment]
Ah okay I see what you're going for now I think. Currently my feeling tends to be that if you want the point/interval and slabs to be less tightly coupled in some customized way then using separate geoms is the best way. Dodging one part of the geom but not another would be hard to stuff into one geom without some fairly complex parameters which would probably end up with syntax about as complicated as what you do with separate geoms.

Have I missed something about your use case?

**Comment by bwiernik** [comment]
No, I think when I was posted the question I hadn't fully realized that the slabs and intervals could also be given as separate geoms. Maybe the best solution would be to add an example like the above to a vignette?

**Comment by mjskay** [comment]
Good idea @bwiernik, I added your example to the slabinterval vignette here: https://mjskay.github.io/ggdist/articles/slabinterval.html#independent-slabs-and-intervals-in-composite-plots

(hope that's alright!)

**Comment by ASKurz** [comment]
Hey @bwiernik and @mjskay, overall I love this method. However, it seems to fail if you try setting a different `.width` value to the intervals. E.g., 

```{r}
df %>%
  ggplot(aes(fill = group, color = group, x = value)) +
  stat_slab(alpha = .3) +
  stat_pointinterval(position = position_dodge(width = .4, preserve = "single"),
                     # This causes problems
                     .width = 0.5) +
  labs(
    title = "stat_slab() and stat_pointinterval()",
    subtitle = "with position_dodge() applied to the intervals",
    y = NULL
  )
```

<img width="797" alt="Screenshot 2024-07-17 at 10 43 10 AM" src="https://github.com/user-attachments/assets/cb9ae93d-09d6-4db4-b455-9b8c11af2354">

**Comment by bwiernik** [comment]
@ASKurz  It appears to be an issue with giving only 1 value for .width rather than a length 2 vector. If you give .width = c(.5, .5), it works

**Comment by ASKurz** [comment]
Huh. I can confirm that works on my end. That syntax seems confusing, though.

**Comment by mjskay** [comment]
Hmmm this odd behavior looks to be because of how `position_dodge(preserve = "single")` treats geoms with groups. Based on this I would recommend not using the `preserve = "single"` option of `position_dodge()` with ggdist geoms. Using `position_dodge()` with the default setting (`preserve = "total"`), or using `ggdist::position_dodgejust()`, should give consistent positioning regardless of the number of intervals specified by `.width`.

For example:

```r
df %>%
  ggplot(aes(fill = group, color = group, x = value)) +
  stat_slab(alpha = .3) +
  stat_pointinterval(position = position_dodgejust(width = .2), justification = 0.1) +
  labs(
    title = "stat_slab() and stat_pointinterval()",
    subtitle = "with position_dodgejust() applied to the intervals",
    y = NULL
  ) +
  scale_y_continuous(breaks = NULL)
```
![image](https://github.com/user-attachments/assets/c867d504-55b5-4e84-8aa5-16423675075c)

And the same, but with `.width = 0.5`:

```r
df %>%
  ggplot(aes(fill = group, color = group, x = value)) +
  stat_slab(alpha = .3) +
  stat_pointinterval(position = position_dodgejust(width = .2), justification = 0.1, .width = 0.5) +
  labs(
    title = "stat_slab() and stat_pointinterval()",
    subtitle = "with position_dodgejust() applied to the intervals",
    y = NULL
  ) +
  scale_y_continuous(breaks = NULL)
```
![image](https://github.com/user-attachments/assets/3ca84457-6b81-42d3-a066-3fc7c561a6fe)

I will update the example in the vignette to use this approach.
