### ISSUE TITLE
geom_raincloud

### ISSUE THREAD

**Issue by jebyrnes** [mjskay/ggdist#28]
Any chance this might happen? I know, I know, this might be an annoying request, but.....

**Comment by mjskay** [comment]
Ha not annoying at all! I'll have to think about it... currently I like the fact that most of the existing geoms fit within a coherent family (and I'm already planning some ways to make that family *more* coherent). 

If by rainclouds you mean a combination of a density *and* jittered points (or maybe a dotplot), I'm not sure exactly how to fit something like that into the existing family. The slabinterval geoms are already composites of three geoms (slab/point/interval) and adding a fourth seems unwieldy to me.

If you just want a density with a dotplot you might be able to do something like this:

```r
library(ggplot2)
library(ggdist)
set.seed(1234)
ggplot(data.frame(x = rnorm(100)), aes(x)) +
  stat_slab() +
  stat_dots(side = "bottom")
```
![image](https://user-images.githubusercontent.com/6345019/93558918-7bea3a00-f94c-11ea-8c24-adac77d27b33.png)


It might help me to better understand the use case / what you're after. Is it something like the above? Is it something with jittering instead?

**Comment by mjskay** [comment]
@jebyrnes I'm closing this for now unless you want to ping again and reopen :). Let me know, I'm happy to discuss!
