### ISSUE TITLE
Feature-request: stat_lineribbon with continuous filling

### ISSUE THREAD

**Issue by Famondir** [mjskay/ggdist#29]
Dear reader,
it would be awesome to get the possibility of filling the stat_lineribbon with a continuous (but maybe binned) colour sclae. This way I hope to prevent the legend in vertical box theme from taking two rows when there are mor than for levels.

Sincerely, Simon

**Comment by mjskay** [comment]
This is possible using the current lineribbon, though admittedly not well documented :). The lineribbon stat generates both a `level` statistic and a `.width` statistic. The `level` statistic is a factor and is assigned to the `fill` aesthetic by default, on the assumption that you want a small number of discrete levels. However, you can override this behavior by assigning the `.width` statistic to the `fill` aesthetic instead, which should produce a continuous scale:

```r
library(ggplot2)
library(ggdist)
set.seed(1234)
ggplot(data.frame(y = rnorm(10000), x = c(1, 2)), aes(x, y)) +
    stat_lineribbon(aes(fill = stat(.width)), .width = ppoints(100))
```
![image](https://user-images.githubusercontent.com/6345019/93559476-d46e0700-f94d-11ea-9ba1-0817f6466655.png)

Hope that helps!
