### ISSUE TITLE
overlap from the bottom

### ISSUE THREAD

**Issue by ASKurz** [mjskay/ggdist#30]
I am summarizing multiple posteriors with `stat_slab()` with value on the x and key on the y. I'd like the densities to overlap a bit, say with `height = 1.5` and `alpha = 3/4`. With this setup, it appears that the densities higher up on the y-axis overlap those on the bottom. Is is possible to reverse this behavior so that the tops of the densities lower on the y overlap the bottoms of the densities above them?

```
library(tidyverse)
library(tidybayes)

n <- 1e4

tibble(x = rnorm(n),
       y = rnorm(n)) %>% 
  gather() %>% 
  ggplot(aes(x = value, y = key)) +
  stat_slab(height = 1.5, color = "black", alpha = 3/4)
```

I get the desired behavior with `ggridges::geom_density_ridges()`.

**Comment by mjskay** [comment]
Ah good catch, that's a bug! It is supposed to work as you expect automatically. Seems I introduced a bug that broke it when I added automatic orientation detection. I just pushed a fix along with some new tests that should catch it if it breaks again.

**Comment by ASKurz** [comment]
woot!
