### ISSUE TITLE
position_jitter() leads to duplication and separation of pointintervals

### ISSUE THREAD

**Issue by dylanhmorris** [mjskay/ggdist#38]
Attempt to jitter a default ``pointinterval`` (or any ``pointinterval`` showing multiple ranges) leads to multiple separated ``pointintervals`` for each set of observations. I believe this occurs because the multiple bounds are constructed by the layering of multiple ``geom_pointinterval()`` instances on top of one another. These are then treated as separate items to jitter by ``position_jitter()``.

 Reproducible example:

```R
library(ggplot2)
library(tidybayes)
library(tibble)
library(magrittr)

## create some data
data <- tibble(
    xs = rep(c(rnorm(1), rnorm(1)), 20),
    ys = rnorm(40),
    groups = rep(rep(1:4), 10))

## plotting gives us overplotted pointintervals
data %>% ggplot(
             aes(x = xs,
                 y = ys,
                 point_fill = factor(groups),
                 group = groups)) +
    stat_pointinterval(shape = 21) +
    scale_fill_distiller()
```
[overplotted.pdf](https://github.com/mjskay/tidybayes/files/4466351/overplotted.pdf)

```R
## we try to jitter and this leads to duplication
jitter <- position_jitter(width = 0.1)
data %>% ggplot(
             aes(x = xs,
                 y = ys,
                 point_fill = factor(groups),
                 group = groups)) +
    stat_pointinterval(shape = 21,
                       position = jitter) +
    scale_fill_distiller()
```
[failed_jitter.pdf](https://github.com/mjskay/tidybayes/files/4466352/failed_jitter.pdf)

**Comment by mjskay** [comment]
Yeah, the list approach won't work because of the need for people to be able to do additional mappings on the .width computed variable. So I think the above workaround of re-using the seed for sub-geoms is the best that can be done in this case.
