### ISSUE TITLE
stats_dots does not reverse when using scale_y_reverse()

### ISSUE THREAD

**Issue by gdbassett** [mjskay/ggdist#54]
scale_y_reverse() does not turn the dot plot upside down.  This is a minor issue, but may be useful for comparing two dot plots, one above the axis and one below.

```
tibble(x=runif(1000)) %>%
  ggplot() +
      ggdist::stat_dots(aes(x=x)) +
      scale_y_reverse()
```

Expected: dots below y axis
Actual: dots above the y axis

**Comment by mjskay** [comment]
Ah interesting... I think this is actually consistent with the semantics of dotplots, which is that they ignore all y axis transformations / scaling (when laid out horizontally). E.g. if you did a log scale transformation you should still see the dots laid out with equal spacing.

If you want dots to hang down, try using `stat_dots(side = "bottom")`. Does that work for your use case?

**Comment by gdbassett** [comment]
Ah, that will work.  Apologize for not reading up on the 'side' parameter first.

**Comment by mjskay** [comment]
No worries! The parameter docs aren't the best currently and there's lots of them
