### ISSUE TITLE
dots when distributions are constants

### ISSUE THREAD

**Issue by ASKurz** [mjskay/ggdist#55]
Consider the following.

```{r}
# load
library(tidyverse)

# simulate
set.seed(1)

data.frame(a = 0,
           b = rnorm(1e4)) %>% 
  pivot_longer(everything()) %>% 
  
  # plot
  ggplot(aes(x = value)) +
  geom_density() +
  facet_wrap(~ name)
```
<img width="819" alt="Screen Shot 2021-02-11 at 2 08 59 PM" src="https://user-images.githubusercontent.com/19917004/107692663-b98c8e00-6c72-11eb-9491-2790f73d722e.png">

Even though the values in the plot for `a` are all at the constant 0, we get a density. Back in the day (at least at version 2.2.1), **tidybayes** (also **ggdist**) would return somewhat similar results with the following.

```{r}
data.frame(a = 0,
           b = rnorm(1e4)) %>% 
  pivot_longer(everything()) %>% 
  
  ggplot(aes(x = value, y = name)) +
  stat_halfeye()
```

Here you'd get a density, along with dot and intervals for `b` and `a` would just be summarized as a dot. You can find a couple examples of this behavior [here](https://bookdown.org/content/3686/ordinal-predicted-variable.html#examples-not-funny.). Now when I try this, I get the error: "Computation failed in `stat_sample_slabinterval()`: need at least two non-NA values to interpolate". Is there a way to recapture the old behavior?

**Comment by mjskay** [comment]
Thanks for catching this, it looks like the bug was introduced by the fact that the cdf is now automatically generated as a computed variable, and the method I used for it was breaking on constant distributions. Should be fixed on master now.

**Comment by ASKurz** [comment]
Success! Thanks, Matt.
