### ISSUE TITLE
support for https://ggplot2.tidyverse.org/reference/expansion.html or https://erocoar.github.io/gghalves/

### ISSUE THREAD

**Issue by xf15** [mjskay/ggdist#61]
I want to plot both model prediction and actual data like 
![image](https://user-images.githubusercontent.com/29473163/112068040-54a43d80-8b26-11eb-8591-28d64497e3b4.png)
but as you see the eyes overlap 

i added expansion function that i have tested to work with ggplot, but it doesn't work here

wouldn't be a problem with gghalves but they don't have eye plot

**Comment by xf15** [comment]
this is the effect i want in case i didn't make it clear 
https://stackoverflow.com/questions/39195748/how-to-change-the-distance-between-categorical-ticks-in-ggplot2

**Comment by mjskay** [comment]
Ah, if I understand correctly you might be looking for the `scale` argument to the stats/geoms in ggdist. If you set it to 0.5 (or less) the two slabs should not overlap. I recently added an example of this here: https://mjskay.github.io/ggdist/articles/slabinterval.html#multiple-slabs-and-intervals-in-composite-plots-1

Let me know if that helps!

**Comment by xf15** [comment]
yes that's it! i should have scrolled to the bottom... thank you!

**Comment by mjskay** [comment]
No prob, happy to help!
