### ISSUE TITLE
`fill = after_scale(alpha(color, .5))` not working with slab fills

### ISSUE THREAD

**Issue by bwiernik** [mjskay/ggdist#62]
I'm trying to use `after_scale()` with `alpha()` to adjust the transparency of slab fills, but it's not working for any of the slab geoms. cf. that it works as expected for `geom_boxplot()`.

```r
library(ggplot2)
library(dplyr)
library(tidyr)
library(palmerpenguins)

set.seed(123)
penguins %>%  
	drop_na(c(species, bill_depth_mm)) %>% 
	ggplot() +
	geom_boxplot(
		aes(x = bill_depth_mm,
				y = species,
				color = species, 
				fill = after_scale(alpha(color, .5))),
		width = .3
	) +
	ggdist::stat_slab(
		aes(x = bill_depth_mm,
				y = species,
				color = species, 
				fill = after_scale(alpha(color, .3))),
		height = .2, 
		position = position_nudge(y = .2)
	) 
```

Also note that functions that adjust the fill color, rather than transparency do work (e.g., `colorspace::darken()` and `colorspace::lighten()`, but `colorspace::adjust_transparency()` does not.

**Comment by mjskay** [comment]
Ah yup, thanks! Should be fixed on master now.
