### ISSUE TITLE
Geom_dots with exact x position 

### ISSUE THREAD

**Issue by mjskay** [mjskay/ggdist#64]
Could do tournament-style selection of points in each stack, ~~alternating whether the points with the largest distance from bin center start at the top or bottom of each stack~~

- [x] basic implementation
- [x] nudging to prevent overlaps
  - [x] in dotplot layout
  - ~~[ ] when `side = "both"` (not sure if this is easily doable, might skip)~~
- [x] tests
- [x] add examples to slabinterval vignette
  - [x] cutoffs with color where classic binning can have problems
- [x] look at adding other layouts?
  - [x] https://observablehq.com/@jtrim-ons/compact-beeswarm-plot
  - ~~[ ] https://www.linkedin.com/pulse/pursuit-diversity-data-visualization-jittering-access-daniel-zvinca/~~

**Comment by jtrim-ons** [comment]
It's really nice that you're considering adding the compact beeswarm!

I thought it might be worth mentioning that Aron Eklund might include it in the beeswarm package at some point (see this [issue](https://github.com/aroneklund/beeswarm/issues/9)), so one option might be to depend on a future version of that package.

And just in case it might be interesting to see, I've very quickly attempted a [piled plot implementation in JavaScript](https://observablehq.com/@jtrim-ons/piled-plot).

**Comment by mjskay** [comment]
Cool! Yeah, if that implementation is put in a self-contained function exported from that package I may use it that way. Otherwise I might take a look at that implementation and adapt it within this package (with your permission of course). Sometimes depending on how things are written (and how much additional dependency baggage I want --- I've been trying to reduce deps for ggdist) that works better.

**Comment by jtrim-ons** [comment]
Thanks for adding the beeswarm!

I was wondering if it would be useful to add a minimum required `beeswarm` version to the DESCRIPTION, as the `compact` option is only available from version 0.4.0? I'm not very experienced with R package versions, so I guess there might be a downside to this that I've overlooked. I'll open a PR just in case it's helpful.
