### ISSUE TITLE
Deprecation warning for inferred ymin/ymax in geom_pointinterval?

### ISSUE THREAD

**Issue by a-hurst** [mjskay/ggdist#65]
Hi there,

I just updated tidybayes along with a few other packages and was very surprised to find that `geom_pointinterval` layers were no longer getting added to my plots. After a bunch of trial and error and digging through issues on this repository + the tidybayes repository, I eventually found the release notes explaining that ymin/ymax are no longer inferred automatically when the input data has `.lower` and `.upper` columns. Anyway, to save future users a similar 20-30 minutes of confusion, would you consider adding a brief informative error or warning to the function when ymin and ymax aren't specified?

Thanks in advance!

P.S. Also, thank you so much for this package and for tidybayes. Together with brms, they've made my life massively easier!

**Comment by mjskay** [comment]
Good point, that's my bad --- I've certainly been there before with changes in other packages :). I'll have to think about what the logic of that should be to prevent false positives.
