### ISSUE TITLE
Manipulating the thickness of interval bar

### ISSUE THREAD

**Issue by arthur-albuquerque** [mjskay/ggdist#70]
Hi, I notice that whenever I apply 2 widths to stat_halfeye (or any stat_), for example, ".width = c(0.5, 0.95)", the thickness of the greater interval gets very thin. Is there any way to manipulate this so I can make it thicker? Thank you

**Comment by mjskay** [comment]
Yes, the default aesthetic mappings of those stats include `size = stat(-.width)`, so you can adjust the scaling of the interval widths using `scale_size_continuous()`. The default:

```r
data.frame(x = rnorm(1000)) %>%
  ggplot(aes(x = x, y = "a")) +
  stat_halfeye()
```
![image](https://user-images.githubusercontent.com/6345019/118585259-1f9b1c80-b75e-11eb-878f-fde5b2fbf740.png)

An adjusted range (the default value of `range` is `c(1,6)`):

```r
data.frame(x = rnorm(1000)) %>% ggplot(aes(x = x, y = "a")) +
  stat_halfeye() +
  scale_size_continuous(range = c(7,15))
```
![image](https://user-images.githubusercontent.com/6345019/118585396-6c7ef300-b75e-11eb-8826-f95c2161b92c.png)


Or if you want to adjust this on a single-geom basis you can use the `interval_size_range` parameter (this parameter is a bit different than above, and has a default value of `c(0.6, 1.4)`):

```r
data.frame(x = rnorm(1000)) %>% 
  ggplot(aes(x = x, y = "a")) + 
  stat_halfeye(interval_size_range = c(2,4))
```
![image](https://user-images.githubusercontent.com/6345019/118585544-bd8ee700-b75e-11eb-8fa1-a21b539573a5.png)

**Comment by arthur-albuquerque** [comment]
Excellent. Thank you very much.
