### ISSUE TITLE
Different set of colors in aes(fill = stat(...))

### ISSUE THREAD

**Issue by arthur-albuquerque** [mjskay/ggdist#71]
Similar to the section "Highlighting and other combinations" in https://mjskay.github.io/ggdist/articles/slabinterval.html, I want to use 2 different colours in distributions using stat_halfeye based on a cutoff. 

However, instead of using the same combination of colours in parallel distributions (just like the reference above), I would like to use different combinations. For example, I would use c("gray85", "skyblue") for the top distribution and c("gray85", "firebrick") for the bottom one.

Unfortunately, I need to plot both distributions in the same geom. I can't find a way to do what I explained above...

Is it possible to do this using stat_halfeye?

Thanks!

**Comment by mjskay** [comment]
If I understand correctly, there are two ways I can think to solve it: one by constructing the necessary combinations of levels of both variables and then applying a custom color scale, and the other by using the `fill` aesthetic for one variable and ggdist's `fill_ramp` aesthetic for the other.

## First method: combine both variables with `interaction()`

We'll use this data:

```r
library(tidyverse)
library(ggdist)

set.seed(1234)
df = data.frame(
  x = rnorm(1000, c(1, 2), 2),
  y = c("a", "b")
)
theme_set(theme_ggdist())
```

My first thought was to try something like this:

```r
df %>%
  ggplot(aes(x = x, y = y, fill = stat(interaction(y, x < 0)))) +
  stat_halfeye()
```
![image](https://user-images.githubusercontent.com/6345019/120093530-84e8f900-c0e0-11eb-8fae-99a243b6fe03.png)

This shows how `interaction()` combines the variables. Now we can apply a custom color scale to get the desired output:

```r
df %>%
  ggplot(aes(x = x, y = y, fill = stat(interaction(y, x < 0)))) +
  stat_halfeye() +
  scale_fill_manual(values = c("gray75", "gray75", "skyblue", "firebrick")) 
```
![image](https://user-images.githubusercontent.com/6345019/120093695-7ea74c80-c0e1-11eb-8d2c-6779d5c73595.png)

This works, but it kind of brittle --- having to set the values manually this way won't work well if you add more variables to the combinations of levels.

## Second method: use fill_ramp

The other option would be to use `fill_ramp`. Something like this:

```r
df %>%
  ggplot(aes(x = x, y = y, fill = y, fill_ramp = stat(x < 0))) +
  stat_halfeye()
```
![image](https://user-images.githubusercontent.com/6345019/120093609-0ccf0300-c0e1-11eb-898b-afc828930ba0.png)

The default settings for the `fill_ramp` scale on discrete variables ramps to 80% white. But we can ramp to `"gray85"` instead. We can also set your custom colors on the fill scale:

```r
df %>%
  ggplot(aes(x = x, y = y, fill = y, fill_ramp = stat(x < 0))) +
  stat_halfeye() +
  scale_fill_ramp_discrete(from = "gray85", range = c(0,1)) +
  scale_fill_manual(values = c("skyblue", "firebrick"))
```
![image](https://user-images.githubusercontent.com/6345019/120093713-8cf56880-c0e1-11eb-8087-544cff54a85e.png)


Does that help?

**Comment by arthur-albuquerque** [comment]
Fantastic. ggdist is such a great package. Congratulations, Matthew. 

Thanks!

**Comment by mjskay** [comment]
Thanks so much! Glad I could help 🙂
