### ISSUE TITLE
Issues with the next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [mjskay/ggdist#72]
Hi Matthew

We are preparing the next ggplot2 release and our reverse dependency tests has showed an issue with ggdist. The issue revolves around a better check of the scale type in `scale_colour_continuous()` and related functions where it is now checked that what comes out of the `type` argument actually matches the aesthetic of the enclosing function. This change means that two of your calls in your unit tests errors:

```r
Error (test.scales.R:67:3): mapping custom aesthetics works
Error: The `type` argument of `scale_colour_discrete()` must return a continuous scale for the colour aesthetic. The provided scale works with the following aesthetics: point_colour
```

and 

```r
Error (test.stat_dist_slabinterval.R:68:3): stat fill aesthetic on halfeye works
Error: The `type` argument of `scale_colour_discrete()` must return a continuous scale for the colour aesthetic. The provided scale works with the following aesthetics: slab_colour
```

We hope to release the next version next week but this issue flew under my radar - let me know if it is possible to prepare a fix by then

best
Thomas

**Comment by mjskay** [comment]
Sure, I'll take a look today or tomorrow and see if I can fix it quick

**Comment by mjskay** [comment]
@thomasp85 thanks for all the help and for putting in the work to check all the zillions of ggplot dependencies, it is really appreciated :)

I think I've got this fixed, I'll submit to cran in the next day or two and post a followup here when it's accepted.

**Comment by mjskay** [comment]
Thanks again Thomas, the fixed version of ggdist is now on CRAN.
