### ISSUE TITLE
IRT-based ICCs

### ISSUE THREAD

**Issue by ASKurz** [mjskay/ggdist#82]
Would the **ggdist** package be a good place to support  item characteristic curves (ICCs) and item information curves (IICs) from item-response theory (IRT) models? This is related to a recent [thread](https://discourse.mc-stan.org/t/item-characteristic-curves-and-item-information-curves-from-item-response-models/22964) on the Stan forums.

**Comment by mjskay** [comment]
Hmmm not sure. I'm assuming you can generate these from a model and then plot them with geom_line or with a lineribbon (if with uncertainty?). I'm not sure what additional support is needed?

**Comment by ASKurz** [comment]
After dwelling on this, more, you're right. The bulk of the labor is in the data wrangling, not the plotting, itself. Thanks for entertaining the thought.

**Comment by mjskay** [comment]
Of course! Always
