### ISSUE TITLE
See if we can merge stat_sample and stat_dist

### ISSUE THREAD

**Issue by mjskay** [mjskay/ggdist#83]
This might require some monkeying around with setup_layer but the general idea would be to allow distribution objects to be mapped onto x or y aesthetics (which should obvs then influence orientation detection) instead of the dist aesthetic. Would have to figure out how to support the old format (string plus args aesthetics). Would want to use this as an opportunity to merge the slab function code together (which probably means dist implementations of point_interval and maybe moving all the density/cdf/quantile code into a separate file).

This is just to reduce the set of geoms and eliminate the annoying usage bug of switching from one form to the other but forgetting to change the name and being confused why stuff isn't working.

Plan is something like:

- [x] allow stat_dist to support dists mapped to `xdist` or `ydist`
  - [x] ~~mapping dist to x or y gets re-written to a dist-based mapping internally~~
  - [x] ~~create `scale_x_dist()` and `scale_y_dist()` to deal with errors on things like this:~~ this turned out to be a bad idea; see https://github.com/mjskay/ggdist/issues/83#issuecomment-973756034
   ```r
   set.seed(1243);
   data.frame(x = c(1,2), y = dist_sample(list(0,0.2))) %>% 
     ggplot(aes(x, y=y)) +
     stat_dist_halfeye(slab_color = "blue", orientation = "vertical") +
     scale_y_continuous()
   ```
- [x] detect dist-like objects being passed to `x` / `y` aesthetic and give a helpful error message.
- [x] #103 
- [x] allow stat_dist to support numerics mapped to x or y by wrapping them in dist_sample()
- [x] #106 
- [x] forward slab function to compute_slab_sample when used on sample data (for densities at least)
- [x] make sure samples with NAs work in stat_dist
- [x] make sure stat_dist supports all arguments from stat_sample:
  - [x] `point_interval`
  - [x] `slab_type = "histogram"`
  - [x] `adjust`
  - [x] `trim`
  - [x] `expand`
  - [x] `breaks`
  - [x] `outline_bars`
- [x] decide what to do about trimming the slab input limits to the limits of sample data on sample distributions (probably want to mimic this behavior from stat_sample_ in stat_dist_). 
  - [x] add new parameter `expand` to handle this: whether the slab only covers the sample data should be determined by `expand`, not `slab_type` (as it is in stat_sample_)
  - [x] make trimming to sample limits depend on `expand`, not `slab_type`
  - [x] make `expand = TRUE` the default for the ccdf / cdf stat_dists
  - [x] make sure compute_limits in stat_dist correctly handles the case where `trim = FALSE` when used on sample data
- [x] drop the limits_function args and whatnot from stat_slabinterval and make these be methods of StatSlabinterval instead (basically, don't want these exposed; this should simplify the public interface)
  - [x] limits_function, limits_args
  - [x] slab_function, slab_args
  - [x] interval_function, interval_args
  - [x] add all of these to `help("ggdist-deprecated")`
- [x] update dotsinterval
  - [x] ensure all args from sample version are in dist version
  - [x] make `quantiles` default to `NA` (but then have it use `100` by default on analytical distributions)
- [x] update lineribbon
- [x] ensure point_interval works on old distributional
- [x] rename:
  - [x] StatSlabinterval -> AbstractStatSlabinterval
  - [x] StatDistXXX -> StatXXX (leave old Dist names as aliases)
  - [x] remember to add StatHistinterval
  - [x] make StatSampleSlabinterval and StatDistSlabinterval aliases for StatSlabinterval
  - [x] search for stat_dist, StatDist, stat_sample, StatSample and switch them
- [x] merge docs and examples from stat_sample_... and stat_dist_... and old stat_slabinterval into new stat_slabinterval
- [x] implement hdci for distributional objects
- [x] rename `stat_dist_slabinterval.R` and `stat_sample_slabinterval.R`
- [x] mention deprecation of stat_dist_ in ggdist-deprecated
- [x] see if `sample_density` is still needed
- [x] simplify `compute_slab_sample`
- [x] simplify `compute_limits_sample`
- [x] simplify `compute_slab_dots_sample`
- [x] split apart shortcut geom docs
- [x] update slabinterval vignette
- [x] update cheat sheet
- [x] test geoms/stats in tidybayes
- [x] do a revdepcheck on this branch
- [x] test on both versions of distributional (or wait till new version is out and #116 is done)
- [x] check coverage

**Comment by bwiernik** [comment]
Could this perhaps be done with S3 dispatch on numeric vs posterior vs distributional arguments?

**Comment by mjskay** [comment]
Unfortunately I think the solution has to be more complicated, because I suspect base ggplot will break if distributional objects are assigned to the `x` or `y` aesthetics.

The sketch of a solution I've been putting together in my head (but haven't tried yet) is something like:
- use `setup_layer()` to detect dist or rvar objects mapped onto `x` or `y` aesthetics and rewrite them into mappings onto `xdist` or `ydist` --- `setup_layer()` is a mostly-internally-used ggplot function that allows you to rewrite the data and the aesthetic mappings early in the pipeline
- would need a helper for later functions to figure out which of `x`/`xdist` or `y`/`ydist` is being used based on some consistent rules. 
- `setup_params()` would then look for either `x` or `y` or `xdist` or `ydist`, requiring only one or the other, and use these to figure out orientation
- `setup_data()` might (I'm not sure about this one) wrap sample data into a distributional object or an rvar. Then by the time `compute_panel()` hits everything is either a dist or an rvar.

**Comment by mitchelloharawild** [comment]
> Unfortunately I think the solution has to be more complicated, because I suspect base ggplot will break if distributional objects are assigned to the `x` or `y` aesthetics.

Have you looked into adding `scale_x_distribution` and `scale_y_distribution` functions with an associated `scale_type(<distribution>)` method and distribution scale ggproto? I think it might be possible to allow `<distribution>` vectors to be specified for `x` and `y` aesthetics, but you might have trouble generating appropriate errors when distributions are used with non-dist supporting functions (say `geom_line()`).

**Comment by mjskay** [comment]
> Have you looked into adding scale_x_distribution and scale_y_distribution functions with an associated scale_type(<distribution>) method and distribution scale ggproto?

Yeah, this is the current approach I am trying. So far it is not without some warts: mostly, users have to know that they can't use `scale_x_continuous()` or `scale_x_discrete()` or any of the `scale_x_[trans]` shortcuts anymore, and the resulting error messages can't be finagled to help them realize this as far as I can tell; also, I think `ggdist` has to be attached to the namespace for ggplot2 to find `scale_x/y_dist()` unless the user manually adds it. I'm going to continue prototyping it this way for a little bit and see how it goes.

The alternatives as I see it now are: (1) use `setup_layer()` to rewrite mappings like `x = [some distributon]` into `xdist = [some distribution]` or (2) keep the implementation of x/y mappings with scale_x_dist / scale_y_dist but also expose (and encourage use of) the `xdist = ...` and `ydist = ...` as the primary aesthetics for distributions or (3) don't support distributions in the `x/y` aesthetics at all (only `xdist` / `ydist`).

I plan at some point to poke some existing users to get them to try this stuff out both to find bugs and see how awkward it is. It's going to be a big change and I want to avoid breaking existing code.

**Comment by mitchelloharawild** [comment]
> Yeah, this is the current approach I am trying. So far it is not without some warts: mostly, users have to know that they can't use `scale_x_continuous()` or `scale_x_discrete()` or any of the `scale_x_[trans]` shortcuts anymore, and the resulting error messages can't be finagled to help them realize this as far as I can tell; 

Yes - I think this is a ggplot2 issue in obscure error measures. I think think unsupported scale type errors can be improved over there, but it's hard to say if this would/could cause new issues elsewhere.

I also think that `scale_x_[trans]` is a design issue in ggplot2, as it forces `scale_x_continuous()`. I wonder if it's possible for ggplot2 to add `scale_x_inherit(...)` to override `...` in the current x scale.

> also, I think `ggdist` has to be attached to the namespace for ggplot2 to find `scale_x/y_dist()` unless the user manually adds it.
Yes, I believe it does.
 
> The alternatives as I see it now are: (1) use `setup_layer()` to rewrite mappings like `x = [some distributon]` into `xdist = [some distribution]` or (2) keep the implementation of x/y mappings with scale_x_dist / scale_y_dist but also expose (and encourage use of) the `xdist = ...` and `ydist = ...` as the primary aesthetics for distributions or (3) don't support distributions in the `x/y` aesthetics at all (only `xdist` / `ydist`).

(1) Sounds hackier than needed, especially when the alternative is for users to learn good ggplot2 practices.
(2) So both are handled in geoms/stats? Why not only allow `x=<dist>` and `y=<dist>`, and require users to know scales better? It has caused some user friction with `tsibble::scale_x_year***()` scales, but I think that is more of a documentation issue. Would you then transform the distribution axis with `scale_x_distribution(trans = ???)`?
(3) Another good option. Generally speaking I like adding some descriptor of axis for the distribution - I currently have some trouble recalling how to plot distributions on specific axis with the `dist` aesthetic alone. To transform the distribution axis, would you use `scale_x_continuous()` or `scale_xdist_continuous()`?

**Comment by mjskay** [comment]
> (3) Another good option. Generally speaking I like adding some descriptor of axis for the distribution - I currently have some trouble recalling how to plot distributions on specific axis with the dist aesthetic alone. To transform the distribution axis, would you use scale_x_continuous() or scale_xdist_continuous()?

`scale_x_continuous()` (or `scale_x_discrete()` for a discrete distribution). This is basically how it works now with the `dist` aesthetic (which I agree is a little error-prone in current usage). Personally I think this works better, as distributions are often combined with other things on the same scale that are not distributions, so we aren't really setting up a scale for distributions per se, but whatever the underlying data type is (this brings up another wrinkle with putting distributions on x/y using `scale_x_dist()`: the `limits()` function doesn't really work with it (thus `xlim`/`ylim` don't really work) because the limits aren't expressed as distributional objects, but as objects of the underlying data type (numeric or integer or what have you).

So, I am kind of coming to the conclusion that unlike things like dates/times, which are legitimately other data types from a scale perspective, distributions don't really match that paradigm. Especially if you add support for other data types in `dist_sample()`: then we'd want dist scales for any other arbitrary data type. So maybe I'll just stick with `xdist` and `ydist` for now.

So I'm now leaning away from (2).

In the absence of option (2), the argument for option (1) is twofold: (A) that it allows x/y axis titles to be generated automatically from variable names and (B) that errors often happen when people accidentally map distributions to `x` or `y` instead of `dist`. Under option (3) I think (B) could be solved with the introduction of `xdist` / `ydist` and an error message if someone maps a distribution to `x` or `y` that tells them to map it to `xdist` or `ydist`. So the only question remaining is if (A) matters.

**Comment by bwiernik** [comment]
Re (A), I think the automatic axis titles are so rarely finalized that it's a minor concern. Users usually have to tweak capitalization/spacing/etc using labs() or similar, so it's not much of a concern.

**Comment by mjskay** [comment]
Yeah makes sense. Barring objections I'll probably go with (3) then.

**Comment by mjskay** [comment]
If anyone out there is interested, this is working now and can be tested on the `unify-dist` branch via:

```r
devtools::install_github("mjskay/ggdist@unify-dist")
```

Under the hood all the `stat_dist_...` stats are now just aliases for their `stat_...` counterparts, which can now take `xdist`/`ydist`/`dist` aesthetics in addition to `x`/`y`. The result is that *in theory* all existing code should "just work", except that you don't need to remember to use `stat_dist_...` anymore in new code, you can just use `stat_...`.

Would be curious if anyone has any particularly weird existing code using ggdist that breaks on this version

**Comment by bwiernik** [comment]
This complicated one using stat_dist_*() works great with the feature branch without code modifications

![image](https://user-images.githubusercontent.com/4773225/144323393-7d4e3fae-8cec-469d-aaf2-05829e0a498b.png)

**Comment by mjskay** [comment]
@bwiernik thanks for testing it, that's great news!

**Comment by dmphillippo** [comment]
I've tested this with the [multinma](https://github.com/dmphillippo/multinma) R package which depends on ggdist - all seems to be working great.

Thank you @mjskay for this excellent package!

**Comment by mjskay** [comment]
Thanks @dmphillippo, that's excellent to hear :). That reminds me I could do a revdepcheck on this branch to stress test it.

**Comment by mjskay** [comment]
this is now on master
