### ISSUE TITLE
ggdist hexagon logo

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [mjskay/ggdist#96]
Hello ggdist team,

I noticed that there was no logo outside of the image of a plot, and so I made a hexagon logo using the colours used in the small logo in the image. My name is Zane Dax and design hexagon logos, trying to build a portfolio and want to share what I made. Hope that you like it, and if you want edits to it let me know.

Thanks.

![ggDist logo](https://user-images.githubusercontent.com/55933131/130291850-ea952d64-1ee6-4283-8926-3085e826c56b.png)

**Comment by mjskay** [comment]
Hi Zane --- thanks! I appreciate you offering your services. You may have missed that ggdist does have an existing logo (figures-source/logo.pdf). At the moment I am happy with the existing logo and plan to continue using it.
