### ISSUE TITLE
stat_halfeye should handle groups with a single data point

### ISSUE THREAD

**Issue by msenn** [mjskay/ggdist#98]
The following data set has only a single observation for group "a":

```r
df <- tibble(group = letters[1:4],
             n = c(1, rep(100, 3))) %>% 
  uncount() %>% 
  mutate(x = rnorm(n()))
```

`stat_halfeye()` throws a warning ("Computation failed in `stat_sample_slabinterval()`:
need at least 2 points to select a bandwidth automatically " and renders an empty plot:

```r
df %>% 
  ggplot(aes(x, group, fill = group)) +
  ggdist::stat_halfeye()
```

This looks to me like a special case of #55 and I would have hoped for the same behavior (i.e. no density but a point, throw a warning).

**Comment by mjskay** [comment]
Ah good point, thanks for catching it! Should be fixed on the github version now.

**Comment by msenn** [comment]
Thanks for fixing!
